(()=>{
  const levels=['Da costruire','Con guida','In autonomia','Per gli altri'];
  const layout=document.createElement('style');layout.textContent='#tab-studio{min-width:0;overflow:hidden}.study-content{width:100%;max-width:100%;min-width:0;overflow:hidden}.study-question,.study-option,.study-card{max-width:100%;min-width:0;overflow-wrap:anywhere;word-break:normal}.study-option{white-space:normal}.study-option small{display:inline;overflow-wrap:anywhere}.study-actions{display:flex;flex-wrap:wrap;gap:10px}';document.head.appendChild(layout);
  const grids={
    comuni:{title:'Materie comuni',hint:'Interrogazione, verifica orale o scritta',items:[['Conoscenza','Riconosco e ricordo le informazioni fondamentali.'],['Comprensione','Spiego con parole mie e collego i concetti.'],['Capacità di analisi','Scompongo un problema e ne individuo le parti.'],['Capacità di sintesi','Seleziono l’essenziale e costruisco una visione coerente.'],['Capacità di esposizione','Comunico i contenuti in modo chiaro e preciso.']]},
    professionali:{title:'Materie professionali',hint:'Esercitazione pratica o progetto tecnico di indirizzo',items:[['Conoscenza anche dei contenuti e delle procedure informatiche','Conosco contenuti, procedure e norme di sicurezza.'],['Comprensione dei contenuti e delle procedure informatiche','Comprendo e applico le istruzioni ricevute.'],['Capacità pratiche e utilizzo delle tecnologie','Uso attrezzature, materiali e tecnologie in modo corretto.'],['Grado di autonomia anche in ambiente digitale','Lavoro con autonomia crescente e so correggere gli errori.']]},
    grafica:{title:'Progettazione e grafica',hint:'Elaborato grafico o progetto del Liceo Artistico',items:[['Conoscenze e procedure tecniche','Conosco tecniche, strumenti, procedure e norme di sicurezza.'],['Competenze-metodo','Seguo un metodo operativo e documento il lavoro.'],['Competenze digitali','Uso lo strumento informatico in modo adeguato e consapevole.'],['Capacità-progetto','Analizzo, progetto e comunico un’idea in modo personale.'],['Impegno','Lavoro con continuità, cura e responsabilità.'],['Partecipazione','Partecipo in modo attivo e costruttivo.'],['Metodo di lavoro','Organizzo tempi, materiali e fasi del progetto in autonomia.']]},
    performance:{title:'Esecuzione e interpretazione',hint:'Esecuzione musicale o performance',items:[['Competenza tecnico-esecutiva anche in ambiente digitale','Mantengo postura, respirazione, coordinazione e controllo del corpo.'],['Competenza esecutivo-strumentale anche in ambiente digitale','Eseguo i brani con tecnica, precisione e uso corretto dello strumento.'],['Capacità di interpretazione','Interpreto il repertorio con coerenza stilistica e originalità espressiva.'],['Conoscenza della specifica letteratura, solistica e d’insieme','Conosco il repertorio affrontato e so collocarlo nel suo contesto.']]}
  };
  let current='comuni', answers={comuni:{},professionali:{},grafica:{},performance:{}};
  function render(){const g=grids[current];document.getElementById('assessmentTitle').textContent=g.title;document.getElementById('assessmentHint').textContent=g.hint;document.getElementById('rubricGrid').innerHTML=g.items.map((r,i)=>`<article class="rubric"><div class="number">${String(i+1).padStart(2,'0')}</div><h3>${r[0]}</h3><p>${r[1]}</p><div class="choices">${levels.map((l,j)=>`<label class="choice"><input type="radio" name="vote-r${i}" value="${j}" ${answers[current][i]===j?'checked':''}>${l}</label>`).join('')}</div></article>`).join('')}
  function calculate(){const vals=Object.values(answers[current]);const total=grids[current].items.length;if(vals.length<total){alert('Completa tutti gli indicatori della griglia per ottenere il voto.');return}const avg=vals.reduce((a,b)=>a+b,0)/total;const vote=Math.max(1,Math.min(10,Math.round(1+(avg/3)*9)));const result=document.getElementById('ptofoResult');result.innerHTML=`<h3>Il tuo voto: ${vote}/10</h3><p>Questo voto nasce dalle risposte che hai dato nella griglia “${grids[current].title}”. Confrontalo con il voto del docente e discutete insieme gli indicatori più alti e quelli da allenare.</p><div class="score-row">${grids[current].items.map((r,i)=>`<div class="score"><strong>${levels[answers[current][i]]}</strong><span>${r[0]}</span></div>`).join('')}</div>`;result.classList.add('show')}
  document.addEventListener('click',e=>{const type=e.target.closest('.assessment-type');if(type){e.preventDefault();e.stopImmediatePropagation();current=type.dataset.assessment;document.querySelectorAll('.assessment-type').forEach(b=>{b.classList.toggle('active',b===type);b.setAttribute('aria-selected',b===type?'true':'false')});render();return}if(e.target.closest('#ptofoDone')){e.preventDefault();e.stopImmediatePropagation();calculate()}},true);
  document.addEventListener('change',e=>{if(e.target.name&&e.target.name.startsWith('vote-r'))answers[current][+e.target.name.slice(6)]=+e.target.value},true);
  render();
})();
