(()=>{
  const levels=['Da costruire','Con guida','In autonomia','Per gli altri'];
  const grids={
    comuni:{title:'Materie comuni',hint:'Interrogazione, verifica orale o scritta',items:[['Conoscenza','Riconosco e ricordo le informazioni fondamentali.'],['Comprensione','Spiego con parole mie e collego i concetti.'],['Capacità di analisi','Scompongo un problema e ne individuo le parti.'],['Capacità di sintesi','Seleziono l’essenziale e costruisco una visione coerente.'],['Capacità di esposizione','Comunico i contenuti in modo chiaro e preciso.']]},
    professionali:{title:'Materie professionali',hint:'Progetto o esercitazione tecnica di indirizzo',items:[['Conoscenza','Riconosco e ricordo le informazioni fondamentali.'],['Comprensione','Spiego con parole mie e collego i concetti.'],['Capacità di analisi','Scompongo un problema e ne individuo le parti.'],['Capacità di sintesi','Seleziono l’essenziale e costruisco una visione coerente.'],['Esercitazioni pratiche e professionali','Trasformo il progetto in un prodotto o in una procedura curata.'],['Laboratorio, autonomia e cura','Organizzo il lavoro, uso strumenti e materiali correttamente e rifletto sugli errori.']]},
    grafica:{title:'Progettazione e grafica',hint:'Tavola, elaborato grafico o progetto visivo',items:[['Conoscenza','Riconosco e ricordo le informazioni fondamentali.'],['Comprensione','Spiego con parole mie e collego i concetti.'],['Capacità di analisi','Scompongo il problema e individuo le parti del progetto.'],['Capacità di sintesi','Seleziono l’essenziale e costruisco una visione coerente.'],['Progettazione ed esercitazioni grafiche','Rappresento un’idea con schizzi, tavole o software, motivando le scelte.'],['Laboratorio, autonomia e cura','Organizzo il lavoro, uso strumenti e software correttamente e rifletto sugli errori.']]},
    performance:{title:'Performance ed esecuzione',hint:'Esecuzione musicale, performance o presentazione pratica',items:[['Conoscenza','Riconosco e ricordo le informazioni fondamentali del brano o della consegna.'],['Comprensione','Spiego con parole mie le scelte e collego i concetti.'],['Capacità di esposizione','Comunico il lavoro in modo chiaro e preciso.'],['Capacità di analisi','Individuo le parti del brano, della consegna o della performance.'],['Pratica musicale e interpretazione','Studio con continuità, controllo tecnica ed espressività e accolgo indicazioni.'],['Laboratorio, autonomia e cura','Preparo il lavoro, uso correttamente strumenti e dispositivi e rifletto sugli errori.']]}
  };
  let current='comuni', answers={comuni:{},professionali:{},grafica:{},performance:{}};
  function render(){const g=grids[current];document.getElementById('assessmentTitle').textContent=g.title;document.getElementById('assessmentHint').textContent=g.hint;document.getElementById('rubricGrid').innerHTML=g.items.map((r,i)=>`<article class="rubric"><div class="number">${String(i+1).padStart(2,'0')}</div><h3>${r[0]}</h3><p>${r[1]}</p><div class="choices">${levels.map((l,j)=>`<label class="choice"><input type="radio" name="vote-r${i}" value="${j}" ${answers[current][i]===j?'checked':''}>${l}</label>`).join('')}</div></article>`).join('')}
  function calculate(){const vals=Object.values(answers[current]);const total=grids[current].items.length;if(vals.length<total){alert('Completa tutti gli indicatori della griglia per ottenere il voto.');return}const avg=vals.reduce((a,b)=>a+b,0)/total;const vote=Math.max(1,Math.min(10,Math.round(1+(avg/3)*9)));const result=document.getElementById('ptofoResult');result.innerHTML=`<h3>Il tuo voto: ${vote}/10</h3><p>Questo voto nasce dalle risposte che hai dato nella griglia “${grids[current].title}”. Confrontalo con il voto del docente e discutete insieme gli indicatori più alti e quelli da allenare.</p><div class="score-row">${grids[current].items.map((r,i)=>`<div class="score"><strong>${levels[answers[current][i]]}</strong><span>${r[0]}</span></div>`).join('')}</div>`;result.classList.add('show')}
  document.addEventListener('click',e=>{const type=e.target.closest('.assessment-type');if(type){e.preventDefault();e.stopImmediatePropagation();current=type.dataset.assessment;document.querySelectorAll('.assessment-type').forEach(b=>{b.classList.toggle('active',b===type);b.setAttribute('aria-selected',b===type?'true':'false')});render();return}if(e.target.closest('#ptofoDone')){e.preventDefault();e.stopImmediatePropagation();calculate()}},true);
  document.addEventListener('change',e=>{if(e.target.name&&e.target.name.startsWith('vote-r'))answers[current][+e.target.name.slice(6)]=+e.target.value},true);
  render();
})();
