(() => {
  const questions = [
    ['pianificazione', 'Quando devi studiare un capitolo nuovo…', ['Inizio a leggere senza obiettivo', 'Guardo struttura e obiettivi, poi formulo domande', 'Copio tutto', 'Aspetto l’ultimo giorno'], 1],
    ['memoria', 'Per ricordare dopo alcuni giorni…', ['Rileggo soltanto', 'Provo a richiamare senza guardare e controllo cosa manca', 'Evidenzio quasi tutto', 'Studio tutto in una volta'], 1],
    ['pianificazione', 'Quando un compito sembra lungo…', ['Lo rimando', 'Lo divido in parti, tempi e primo passo', 'Faccio parti casuali', 'Cerco subito una soluzione pronta'], 1],
    ['attenzione', 'Durante una sessione di studio il telefono…', ['Resta accanto con le notifiche', 'È lontano o silenziato per un tempo stabilito', 'Lo controllo spesso', 'Non cambia la concentrazione'], 1],
    ['monitoraggio', 'Se sbagli un esercizio…', ['Guardi subito la soluzione', 'Individui il tipo di errore e riprovi', 'Lo salti', 'Memorizzi il risultato'], 1],
    ['memoria', 'Per preparare un’interrogazione…', ['Rileggi dall’inizio alla fine', 'Prepari domande e provi una spiegazione senza appunti', 'Impari frasi a memoria', 'Ripeti solo la sera prima'], 1],
    ['elaborazione', 'Per collegare argomenti diversi…', ['Li tieni separati', 'Confronti cause, effetti, esempi e parole chiave', 'Sottolinei ogni riga', 'Aspetti che il collegamento venga da sé'], 1],
    ['comprensione', 'Quando non capisci una consegna…', ['Parti comunque', 'La riscrivi con parole tue e chiarisci il prodotto richiesto', 'Copi un esempio', 'Rinunci'], 1],
    ['memoria', 'Una sessione efficace termina con…', ['Un’altra rilettura', 'Un breve richiamo senza libro e il prossimo passo', 'Altre evidenziazioni', 'Nessuna verifica'], 1],
    ['monitoraggio', 'Per capire se un metodo funziona…', ['Conti solo il tempo trascorso', 'Controlli cosa sai fare senza aiuti e modifichi il piano', 'Aspetti il voto', 'Cambi metodo ogni giorno'], 1],
    ['attenzione', 'Quando la concentrazione cala…', ['Continui senza capire', 'Fai una pausa breve e riparti con un obiettivo preciso', 'Apri i social', 'Abbandoni la materia'], 1],
    ['elaborazione', 'Dopo aver studiato un concetto nuovo…', ['Lo lasci isolato', 'Crei un esempio tuo e spieghi dove può essere usato', 'Ricopi la definizione', 'Memorizzi solo le parole in grassetto'], 1],
    ['ambiente', 'Dove riesci più spesso a studiare?', ['In un posto sempre diverso, senza un piano', 'In un posto abbastanza stabile, preparato prima', 'Solo quando tutti gli altri hanno finito', 'Non ho mai osservato questa differenza'], 1],
    ['ambiente', 'Quando a casa arrivano rumori o interruzioni…', ['Abbandono subito il compito', 'Prevedo una soluzione: pausa, cuffie, altro spazio o avviso agli altri', 'Continuo anche se non capisco più', 'Aspetto che il problema sparisca'], 1],
    ['motivazione', 'Che cosa ti aiuta di più a iniziare?', ['Un voto o una pressione esterna', 'Un obiettivo concreto e il collegamento con qualcosa che mi interessa', 'Sapere che manca poco tempo', 'Una soluzione già pronta'], 1],
    ['motivazione', 'Quando un argomento diventa difficile…', ['Penso che non faccia per me', 'Cerco quale passaggio posso capire o provare per primo', 'Cambio subito materia', 'Aspetto che qualcuno lo risolva'], 1],
    ['aspettative', 'Che cosa vorresti ottenere da questo percorso?', ['Solo finire velocemente', 'Conoscere meglio come studio e portare via una strategia concreta', 'Una risposta uguale per tutti', 'Un voto senza dover provare'], 1],
    ['aspettative', 'Come capirai che il tuo metodo sta migliorando?', ['Quando studio più ore', 'Quando ricordo e so applicare ciò che ho studiato con meno aiuti', 'Quando il compito sembra più facile', 'Quando non commetto mai errori'], 1]
  ];

  const strategies = [
    { name: 'Richiamo attivo', summary: 'Ricostruisci ciò che sai senza guardare il materiale.', when: 'Dopo una prima comprensione e prima di una verifica.', steps: ['Studia un segmento breve', 'Chiudi o copri il materiale', 'Ricostruisci idee e passaggi', 'Riapri, controlla e correggi'], example: 'Dopo due pagine, scrivi cinque idee a memoria. Confronta con il testo e aggiungi in un altro colore ciò che mancava.', avoid: 'Rileggere mentre provi a ricordare: trasforma il richiamo in riconoscimento.', practice: 'Copri il testo e scrivi cinque idee essenziali; riaprilo e correggi in un altro colore.' },
    { name: 'Pratica distribuita', summary: 'Riprendi lo stesso contenuto in momenti separati invece di concentrarlo alla vigilia.', when: 'Per conoscenze che devono durare settimane o mesi.', steps: ['Prima comprensione oggi', 'Richiamo breve domani', 'Nuovo richiamo tra 3 giorni', 'Controllo finale dopo una settimana'], example: 'Crea quattro richiami da 8–10 minuti. Ogni volta parti senza libro e dedica più tempo a ciò che non emerge.', avoid: 'Ripetere identicamente: gli intervalli devono contenere richiamo e correzione.', practice: 'Crea ora tre appuntamenti di richiamo: domani, tra tre giorni e tra una settimana; scrivi cosa controllerai.' },
    { name: 'Alternanza degli esercizi', summary: 'Mescola problemi o argomenti collegati per imparare a scegliere la procedura.', when: 'Quando sai già svolgere almeno un esempio di ogni tipo.', steps: ['Seleziona 2–3 tipi collegati', 'Mescolali senza etichette', 'Scegli il metodo prima di agire', 'Spiega l’indizio che ti ha guidato'], example: 'Alterna causa/conseguenza, confronto e cronologia; per ogni domanda dichiara quale struttura userai e perché.', avoid: 'Alternare troppo presto, prima di avere capito i casi di base.', practice: 'Formula tre domande diverse sul testo: una di causa, una di confronto e una di applicazione; rispondi scegliendo il metodo.' },
    { name: 'Elaborazione', summary: 'Collega il nuovo a ciò che sai attraverso perché, esempi e conseguenze.', when: 'Quando vuoi comprendere relazioni, non soltanto definizioni.', steps: ['Individua l’idea centrale', 'Chiedi “perché è così?”', 'Crea un esempio personale', 'Collega a un concetto già noto'], example: 'Per ogni concetto completa: “Questo accade perché…”, “Un esempio è…”, “Si collega a…”.', avoid: 'Inventare collegamenti plausibili ma sbagliati: controllali sempre nel materiale.', practice: 'Rispondi per iscritto a tre domande: perché è importante, quale esempio nuovo puoi creare, a cosa già noto si collega.' },
    { name: 'Doppia codifica', summary: 'Combina parole e rappresentazioni visive che mostrano davvero le relazioni.', when: 'Per processi, strutture, sequenze e confronti.', steps: ['Seleziona massimo 5–7 idee', 'Scegli forma: flusso, mappa o confronto', 'Collega con frecce etichettate', 'Spiega il disegno senza leggere'], example: 'Trasforma il testo in quattro nodi collegati. Ogni freccia deve dire “causa”, “produce”, “contrasta” o un’altra relazione.', avoid: 'Decorare o ricopiare frasi intere: l’immagine deve aggiungere struttura.', practice: 'Crea una mini-mappa di massimo cinque nodi; usa frecce con parole-relazione e poi spiegala senza leggere.' },
    { name: 'Gestione dell’attenzione', summary: 'Prepara ambiente, obiettivo, durata e pausa prima di cominciare.', when: 'Quando inizi tardi, interrompi spesso o perdi il filo.', steps: ['Definisci un prodotto concreto', 'Allontana le distrazioni', 'Imposta un blocco breve', 'Chiudi con richiamo e prossimo passo'], example: 'Obiettivo: “ricostruire quattro idee”, 15 minuti, telefono fuori portata, una scheda aperta, pausa finale.', avoid: 'Misurare solo il tempo: il blocco deve terminare con un risultato osservabile.', practice: 'Scrivi un obiettivo verificabile, libera il piano di lavoro, silenzia il telefono e imposta un blocco di 12 minuti.' },
    { name: 'Autospiegazione', summary: 'Rendi esplicito perché compi un passaggio e come si collega al precedente.', when: 'Durante problemi, analisi di testi, procedure e dimostrazioni.', steps: ['Nomina il passaggio', 'Spiega perché serve', 'Collegalo a ciò che precede', 'Controlla se sapresti insegnarlo'], example: 'Dopo ogni paragrafo completa ad alta voce: “Qui l’autore dice…; serve perché…; si collega a…”.', avoid: 'Ripetere le stesse parole del testo senza esplicitare relazioni.', practice: 'Per ciascun paragrafo scrivi una frase che inizi con “Questo passaggio è importante perché…”.' },
    { name: 'Registro degli errori', summary: 'Trasforma l’errore in informazione su causa e prossima strategia.', when: 'Dopo esercizi, interrogazioni simulate e autocorrezioni.', steps: ['Descrivi l’errore preciso', 'Classifica la causa', 'Scrivi la correzione', 'Programma una nuova prova simile'], example: 'Tabella a tre colonne: errore (“confondo le cause”), causa (“lista senza relazioni”), rimedio (“mappa causale e richiamo domani”).', avoid: 'Scrivere soltanto “distrazione”: serve una causa su cui puoi intervenire.', practice: 'Dopo il test finale registra un errore o un’incertezza, la causa probabile e la prossima azione concreta.' }
  ];

  const samples = [
    { title: 'Storia · La stampa e la circolazione delle idee', label: 'Storia', focus: 'In che modo la stampa modificò produzione, controllo e diffusione delle idee in Europa?', text: ['A metà del Quattrocento la stampa a caratteri mobili rese più rapida la produzione dei libri. Prima, copiare un testo a mano richiedeva molto tempo e ogni esemplare poteva presentare differenze. Con caratteri riutilizzabili, carta e torchio, uno stesso testo poteva essere riprodotto in molte copie relativamente uniformi.', 'La maggiore disponibilità di libri non rese però tutti immediatamente lettori. Il costo diminuì, ma alfabetizzazione, lingua e accesso continuarono a creare differenze. Le botteghe tipografiche divennero luoghi in cui si incontravano artigiani, studiosi e commercianti; sceglievano quali opere pubblicare valutando interesse, rischi e possibilità di vendita.', 'La stampa accelerò la circolazione di idee religiose, scientifiche e politiche. Proprio per questo autorità civili e religiose tentarono di controllarla con privilegi, autorizzazioni e indici di opere proibite. La nuova tecnologia non produsse automaticamente libertà o verità: ampliò il pubblico e rese più veloce sia la diffusione delle conoscenze sia quella di errori e conflitti.'], prompts: ['Quali differenze introduce la stampa rispetto alla copia manuale?', 'Perché l’accesso ai libri rimase diseguale?', 'Qual è il rapporto tra maggiore circolazione e tentativi di controllo?'], model: 'Caratteri riutilizzabili e torchio aumentano velocità e uniformità delle copie. L’accesso resta diseguale per costi, alfabetizzazione e lingua. La circolazione più ampia delle idee aumenta il pubblico ma spinge le autorità a creare nuovi controlli.' },
    { title: 'Scienze · Effetto serra e cambiamento climatico', label: 'Scienze', focus: 'Perché l’effetto serra naturale è necessario, mentre il suo rafforzamento produce rischi?', text: ['La superficie terrestre riceve energia dal Sole e ne restituisce una parte sotto forma di radiazione infrarossa. Alcuni gas atmosferici, tra cui vapore acqueo, anidride carbonica e metano, assorbono e riemettono parte di questa energia. Questo effetto serra naturale mantiene temperature compatibili con la vita come la conosciamo.', 'Le attività umane modificano l’equilibrio aumentando la concentrazione di alcuni gas serra. Combustione di carbone, petrolio e gas, cambiamenti nell’uso del suolo, allevamenti e processi industriali contribuiscono in misura diversa. Più energia resta nel sistema climatico e cambiano temperature medie, precipitazioni, ghiacci ed eventi estremi.', 'Un singolo giorno freddo non smentisce il riscaldamento globale: il meteo descrive condizioni locali e di breve durata, il clima osserva andamenti su periodi lunghi e aree vaste. Le decisioni richiedono quindi serie di dati, modelli controllati e confronto tra molte evidenze, non un esempio isolato.'], prompts: ['Quale funzione svolge l’effetto serra naturale?', 'Quali attività rafforzano l’effetto serra?', 'Perché un episodio meteorologico non basta a descrivere il clima?'], model: 'L’effetto naturale trattiene energia e rende abitabile il pianeta. Le attività umane aumentano gas come CO₂ e metano. Il meteo riguarda eventi brevi e locali, mentre il clima emerge da serie lunghe e vaste di osservazioni.' },
    { title: 'Progettazione · Dal bozzetto al prototipo', label: 'Area artistico-professionale', focus: 'Perché il prototipo non è una copia imperfetta del prodotto finale, ma uno strumento per decidere?', text: ['Un bozzetto rende visibile un’idea iniziale: proporzioni, ritmo, materiali, funzione e atmosfera. Non deve risolvere ogni dettaglio. Serve soprattutto a generare alternative rapidamente e a rendere discutibili scelte che, finché restano soltanto nella mente, sono difficili da confrontare.', 'Il prototipo traduce alcune di quelle scelte in una forma che può essere osservata o provata. Può essere una maquette, un campione, una sequenza grafica, una registrazione di prova o una simulazione digitale. La sua fedeltà dipende dalla domanda: se bisogna controllare una proporzione non è necessario rifinire la superficie; se si valuta il timbro, invece, il materiale può diventare decisivo.', 'Provare presto riduce il costo degli errori e produce informazioni. Il feedback è utile quando riguarda criteri dichiarati — funzione, leggibilità, equilibrio, resistenza, espressività — e conduce a una modifica verificabile. Documentare versioni e decisioni permette di distinguere un cambiamento casuale da un miglioramento motivato.'], prompts: ['Che funzione ha il bozzetto?', 'Da che cosa dipende la fedeltà del prototipo?', 'Quando un feedback produce un miglioramento verificabile?'], model: 'Il bozzetto genera e confronta alternative. Il livello di fedeltà dipende dalla domanda da verificare. Il feedback è utile quando usa criteri dichiarati e porta a una modifica controllabile e documentata.' }
  ];

  const visualMaps = {
    'Storia': { title: 'Mappa causale · la stampa', nodes: ['Caratteri mobili + torchio', 'Più copie e maggiore uniformità', 'Accesso ancora diseguale', 'Circolazione più rapida', 'Nuovi controlli e conflitti'], links: ['produce', 'ma non elimina', 'permette', 'spinge a'] },
    'Scienze': { title: 'Schema processo · effetto serra', nodes: ['Energia dal Sole', 'Radiazione infrarossa', 'Gas serra naturali', 'Equilibrio climatico', 'Attività umane → aumento gas'], links: ['si trasforma in', 'viene assorbita da', 'mantengono', 'si altera con'] },
    'Area artistico-professionale': { title: 'Mappa di progetto · dal bozzetto al prototipo', nodes: ['Idea e alternative', 'Bozzetto: rendere visibile', 'Prototipo: provare una scelta', 'Feedback su criteri', 'Modifica documentata'], links: ['si chiarisce nel', 'si verifica nel', 'si valuta con', 'porta a'] }
  };
  function renderStudyMap(sample) {
    const map = visualMaps[sample.label];
    return `<section class="study-maps" aria-labelledby="map-title"><div class="study-map-head"><div><div class="kicker">Esempio sul brano</div><h4 id="map-title">${map.title}</h4></div><span>Osserva le relazioni, non copiare le frasi</span></div><div class="map-flow">${map.nodes.map((node, index) => `<div class="map-node"><span>${String(index + 1).padStart(2, '0')}</span><b>${node}</b>${index < map.links.length ? `<small>${map.links[index]}</small>` : ''}</div>`).join('')}</div><div class="map-note"><strong>Come leggerla.</strong> Le frecce rispondono alla domanda-guida: ogni nodo è breve, ogni relazione dice che cosa cambia o dipende da che cosa. Ora prova a costruire una versione tua con massimo 5–7 nodi.</div></section>`;
  }
  const state = { step: 0, answers: [], chosen: [], exercise: [], reflection: '', sample: 0, recall: '', reveal: false };
  const content = document.getElementById('studyContent');
  const button = (label, action, disabled = false, secondary = false) => `<button class="btn ${secondary ? 'secondary' : ''}" data-study-action="${action}" ${disabled ? 'disabled' : ''}>${label}</button>`;
  const exerciseCheck = (index, label) => `<label class="guided-check"><input type="checkbox" name="study-exercise${index}" ${state.exercise[index] ? 'checked' : ''}><span>${label}</span></label>`;

  function updateSteps() {
    document.querySelectorAll('.study-step').forEach((step, index) => step.classList.toggle('active', index === state.step));
  }

  function render() {
    updateSteps();
    if (state.step === 0) {
      const questionGroups = [['Abitudini di studio', questions.slice(0, 12)], ['Ambiente domestico', questions.slice(12, 14)], ['Motivazioni', questions.slice(14, 16)], ['Aspettative', questions.slice(16, 18)]];
      let questionIndex = 0;
      content.innerHTML = `<h3>1. Autoplacement: come studi oggi?</h3><p>Rispondi sulle tue abitudini reali, sull’ambiente in cui studi e su ciò che ti motiva. Non ci sono risposte giuste o sbagliate: servono a costruire un percorso utile per te. Tempo previsto: 15 minuti.</p>${questionGroups.map(([title, group]) => `<section class="study-question-group"><h4>${title}</h4>${group.map(question => { const index = questionIndex++; return `<div class="study-question"><p>${index + 1}. ${question[1]}</p>${question[2].map((option, optionIndex) => `<label class="study-option"><input type="radio" name="study-q${index}" value="${optionIndex}" ${state.answers[index] === optionIndex ? 'checked' : ''}><span>${option}</span></label>`).join('')}</div>`; }).join('')}</section>`).join('')}<div class="study-actions">${button('Calcola la mia mappa', 'diagnose')}</div>`;
    } else if (state.step === 1) {
      const areaNames = { pianificazione: 'Pianificazione', memoria: 'Memoria e richiamo', attenzione: 'Gestione dell’attenzione', monitoraggio: 'Controllo del metodo', elaborazione: 'Elaborazione e collegamenti', comprensione: 'Comprensione della consegna', ambiente: 'Ambiente domestico', motivazione: 'Motivazione', aspettative: 'Aspettative personali' };
      const scores = {};
      questions.forEach((question, index) => {
        const area = question[0];
        scores[area] ||= [];
        scores[area].push(state.answers[index] === question[3] ? 3 : 1);
      });
      const rows = Object.entries(scores).map(([area, values]) => [areaNames[area], values.reduce((a, b) => a + b, 0) / values.length]);
      const strongest = [...rows].sort((a, b) => b[1] - a[1])[0][0];
      const weakest = [...rows].sort((a, b) => a[1] - b[1])[0][0];
      content.innerHTML = `<h3>2. La tua mappa</h3><p><strong>Punto di forza:</strong> ${strongest}. <strong>Area da allenare:</strong> ${weakest}. Il profilo descrive abitudini modificabili, non capacità fisse.</p>${rows.map(([name, score]) => `<div class="study-card"><h4>${name} · ${score < 1.6 ? 'da allenare' : score < 2.6 ? 'in costruzione' : 'punto di forza'}</h4><div class="progress"><i style="width:${Math.round(score / 3 * 100)}%"></i></div></div>`).join('')}<div class="study-actions">${button('Rivedi le risposte', 'back', false, true)}${button('Conosci le strategie', 'strategies')}</div>`;
    } else if (state.step === 2) {
      content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 3 · Capire prima di scegliere</div><h3>Come funzionano le strategie efficaci</h3><p>Apri le schede, osserva la procedura in quattro mosse e poi scegli esattamente due strategie da sperimentare. Tempo previsto: 15–20 minuti.</p></div><div class="study-choice-count" id="strategyCount">${state.chosen.length}/2 scelte</div></div><div class="strategy-library">${strategies.map((strategy, index) => `<article class="strategy-guide"><div class="strategy-guide-top"><div><span class="strategy-index">${String(index + 1).padStart(2, '0')}</span><h4>${strategy.name}</h4><p>${strategy.summary}</p></div><label class="strategy-pick"><input type="checkbox" name="study-strategy" value="${index}" ${state.chosen.includes(index) ? 'checked' : ''}><span>Scegli questa</span></label></div><details><summary>Scopri come funziona</summary><div class="strategy-detail"><div class="strategy-when"><b>Quando è utile</b><span>${strategy.when}</span></div><div class="study-infographic" aria-label="Procedura in quattro passaggi per ${strategy.name}">${strategy.steps.map((step, stepIndex) => `<div><span>${stepIndex + 1}</span><b>${step}</b></div>`).join('')}</div><div class="strategy-examples"><div><b>Esempio concreto</b><p>${strategy.example}</p></div><div><b>Errore da evitare</b><p>${strategy.avoid}</p></div></div><div class="strategy-try"><b>Prova lampo</b>${strategy.practice}</div></div></details></article>`).join('')}</div><div class="study-actions">${button('Torna alla mappa', 'back', false, true)}${button('Prepara la prova guidata', 'exercise', state.chosen.length !== 2)}</div>`;
    } else if (state.step === 3) {
      const sample = samples[state.sample];
      const selectedStrategies = state.chosen.map(index => strategies[index]);
      content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 4 · Laboratorio</div><h3>Prova guidata · 20 minuti</h3><p>Non devi cercare nulla: scegli uno dei tre testi e segui i passaggi nell’ordine. Spunta una fase soltanto quando l’hai conclusa.</p></div><div class="study-choice-count">${state.exercise.filter(Boolean).length}/5 fasi</div></div><div class="sample-picker" role="group" aria-label="Scegli il testo di prova">${samples.map((item, index) => `<button data-study-sample="${index}" class="sample-button ${state.sample === index ? 'active' : ''}" aria-pressed="${state.sample === index}"><b>${item.label}</b><span>${item.title.replace(`${item.label} · `, '')}</span></button>`).join('')}</div><article class="practice-text"><div class="kicker">Testo didattico originale StradiLab</div><h4>${sample.title}</h4>${sample.text.map(paragraph => `<p>${paragraph}</p>`).join('')}</article>${renderStudyMap(sample)}<aside class="pair-check"><div><div class="kicker">Facoltativo · controllo a coppie</div><h4>Confronta la tua mappa con un compagno</h4><p>Mostratevi solo i nodi e le frecce, senza correggervi a vicenda. Ognuno indica una relazione chiara e una da rendere più precisa.</p><ul><li>Quale nodo avete scelto entrambi?</li><li>Quale freccia spiega meglio il brano?</li><li>Che cosa cambiereste, e perché?</li></ul></div><label class="guided-check"><input type="checkbox" name="study-pair-check"><span>Abbiamo confrontato le mappe e motivato almeno una modifica.</span></label></aside><div class="guided-practice">
        <section class="guided-step"><div class="guided-step-number">1<span>2 min</span></div><div><h4>Orienta la lettura</h4><p>Leggi titolo e domanda-guida. Trasformala in un obiettivo: al termine dovrai rispondere senza guardare.</p><div class="guided-prompt"><b>Domanda-guida</b>${sample.focus}</div>${exerciseCheck(0, 'Ho capito quale risposta devo costruire.')}</div></section>
        <section class="guided-step"><div class="guided-step-number">2<span>3 min</span></div><div><h4>Prima lettura attiva</h4><p>Leggi il testo una volta. Dopo ogni paragrafo scrivi a margine una frase di massimo sette parole. Non evidenziare più di una frase per paragrafo.</p>${exerciseCheck(1, 'Ho individuato l’idea centrale dei tre paragrafi.')}</div></section>
        <section class="guided-step"><div class="guided-step-number">3<span>5 min</span></div><div><h4>Applica: ${selectedStrategies[0].name}</h4><p>${selectedStrategies[0].practice}</p><div class="guided-hint"><b>Non saltare il controllo.</b> ${selectedStrategies[0].avoid}</div>${exerciseCheck(2, `Ho applicato ${selectedStrategies[0].name.toLowerCase()} e controllato il risultato.`)}</div></section>
        <section class="guided-step"><div class="guided-step-number">4<span>5 min</span></div><div><h4>Applica: ${selectedStrategies[1].name}</h4><p>${selectedStrategies[1].practice}</p><div class="guided-hint"><b>Non saltare il controllo.</b> ${selectedStrategies[1].avoid}</div>${exerciseCheck(3, `Ho applicato ${selectedStrategies[1].name.toLowerCase()} e controllato il risultato.`)}</div></section>
        <section class="guided-step"><div class="guided-step-number">5<span>5 min</span></div><div><h4>Richiamo finale senza testo</h4><p>Copri il brano e rispondi alle tre domande. Non cercare frasi perfette: rendi visibili ciò che ricordi e i collegamenti.</p><ol class="recall-prompts">${sample.prompts.map(prompt => `<li>${prompt}</li>`).join('')}</ol><label class="recall-field"><span>Scrivi qui la tua ricostruzione</span><textarea id="studyRecall" rows="7">${state.recall}</textarea></label><button class="btn secondary" data-study-action="model" ${state.recall.trim().length < 30 ? 'disabled' : ''}>${state.reveal ? 'Nascondi la soluzione-modello' : 'Confronta con la soluzione-modello'}</button>${state.reveal ? `<div class="model-answer"><b>Soluzione-modello</b><p>${sample.model}</p><span>Non deve essere identica alla tua: controlla presenza delle relazioni essenziali e correggi in un altro colore.</span></div>` : ''}${exerciseCheck(4, 'Ho risposto senza testo, confrontato e corretto ciò che mancava.')}</div></section>
      </div><div class="study-question reflection-block"><p>Che cosa hai notato?</p>${[['utile', 'Le strategie mi hanno mostrato cosa sapevo davvero.'], ['difficile', 'È stato difficile, ma ora so quale passaggio allenare.'], ['riprovare', 'Riproverò con un testo più breve e lo stesso procedimento.']].map(([value, label]) => `<label class="study-option"><input type="radio" name="study-reflection" value="${value}" ${state.reflection === value ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div><div class="study-actions">${button('Torna alle strategie', 'back', false, true)}${button('Costruisci il piano', 'plan', state.exercise.length !== 5 || !state.exercise.every(Boolean) || !state.reflection)}</div>`;
    } else {
      content.innerHTML = `<h3>5. Il tuo piano per 7 giorni</h3><p>Trasforma l’esperimento in una routine breve e verificabile. Tempo previsto: 10 minuti.</p><div class="study-card"><h4>La mia routine</h4><p><strong>Prima:</strong> definisco un obiettivo concreto. <strong>Durante:</strong> uso ${state.chosen.map(index => strategies[index].name).join(' e ')}. <strong>Dopo:</strong> richiamo senza libro e registro un errore utile.</p></div><div class="study-card"><h4>Impegno concreto</h4><p>Per sette giorni farò quattro blocchi da 25 minuti, con telefono fuori portata. Riprenderò lo stesso contenuto in almeno tre giorni diversi e controllerò ciò che ricordo senza aiuti.</p></div><section class="study-recap"><div class="kicker">Il tuo riepilogo</div><h4>Che cosa hai scelto e sperimentato</h4><p><strong>Brano:</strong> ${samples[state.sample].title}</p><p><strong>Strategie:</strong> ${state.chosen.map(index => strategies[index].name).join(' · ')}</p><p><strong>La tua riflessione:</strong> ${state.reflection}</p><p><strong>Passo successivo:</strong> riprendi la mappa e il richiamo tra tre giorni, poi registra che cosa è migliorato.</p></section><div class="study-result show"><strong>Percorso completato · circa 65–70 minuti</strong><br>Hai osservato il tuo metodo, riconosciuto punti di forza e fragilità, compreso e provato due strategie e progettato un’applicazione settimanale.<br><span class="welcome-line">Continua così: ogni prova ti aiuta a conoscere meglio come impari.</span><br><strong>Benvenuto allo Stradivari!</strong></div><div class="study-actions">${button('Rivedi la prova', 'back', false, true)}${button('Ricomincia', 'restart')}</div>`;
    }

    content.querySelectorAll('input[name="study-strategy"]').forEach(input => input.addEventListener('change', () => {
      const selected = [...content.querySelectorAll('input[name="study-strategy"]:checked')].map(item => Number(item.value));
      if (selected.length > 2) { input.checked = false; return; }
      state.chosen = selected;
      document.getElementById('strategyCount').textContent = `${selected.length}/2 scelte`;
      content.querySelector('[data-study-action="exercise"]').disabled = selected.length !== 2;
    }));
    content.querySelectorAll('input[name^="study-exercise"]').forEach((input, index) => input.addEventListener('change', () => { state.exercise[index] = input.checked; render(); }));
    content.querySelectorAll('input[name="study-reflection"]').forEach(input => input.addEventListener('change', () => { state.reflection = input.value; render(); }));
    const recall = document.getElementById('studyRecall');
    recall?.addEventListener('input', () => {
      state.recall = recall.value;
      const modelButton = content.querySelector('[data-study-action="model"]');
      if (modelButton) modelButton.disabled = state.recall.trim().length < 30;
    });
  }

  document.addEventListener('click', event => {
    const sampleTrigger = event.target.closest('[data-study-sample]');
    if (sampleTrigger) {
      state.sample = Number(sampleTrigger.dataset.studySample);
      state.exercise = Array(5).fill(false);
      state.reflection = '';
      state.recall = '';
      state.reveal = false;
      render();
      return;
    }
    const trigger = event.target.closest('[data-study-action]');
    if (!trigger) return;
    const action = trigger.dataset.studyAction;
    if (action === 'diagnose') {
      state.answers = questions.map((_, index) => { const checked = document.querySelector(`input[name="study-q${index}"]:checked`); return checked ? Number(checked.value) : undefined; });
      if (state.answers.some(value => value === undefined)) { alert('Completa tutte le domande per ottenere la mappa.'); return; }
      state.step = 1;
    } else if (action === 'strategies') state.step = 2;
    else if (action === 'exercise') { state.exercise = Array(5).fill(false); state.reflection = ''; state.recall = ''; state.reveal = false; state.step = 3; }
    else if (action === 'model') { state.reveal = !state.reveal; render(); return; }
    else if (action === 'plan') state.step = 4;
    else if (action === 'back') state.step = Math.max(0, state.step - 1);
    else if (action === 'restart') Object.assign(state, { step: 0, answers: [], chosen: [], exercise: [], reflection: '', sample: 0, recall: '', reveal: false });
    render();
    content.scrollIntoView({ behavior: 'smooth', block: 'start' });
    document.dispatchEvent(new CustomEvent('stradivari-progress'));
  });

  window.StradivariStudy = { completed: () => state.step === 4 ? 5 : state.step, total: 5, getResults: () => ({ step: state.step, sample: samples[state.sample]?.title, strategies: state.chosen.map(index => strategies[index]?.name).filter(Boolean), reflection: state.reflection, completed: state.step === 4 }) };
  render();
})();
