(() => {
  const questions = [
    ['pianificazione', 'Quando devi studiare un capitolo nuovo…', ['Inizio a leggere senza obiettivo', 'Guardo struttura e obiettivi, poi formulo domande', 'Copio tutto', 'Aspetto l’ultimo giorno'], 1],
    ['memoria', 'Per ricordare dopo alcuni giorni…', ['Rileggo soltanto', 'Provo a richiamare senza guardare e controllo cosa manca', 'Evidenzio quasi tutto', 'Studio tutto in una volta'], 1],
    ['pianificazione', 'Quando un compito sembra lungo…', ['Lo rimando', 'Lo divido in parti, tempi e primo passo', 'Faccio parti casuali', 'Cerco subito una soluzione pronta'], 1],
    ['attenzione', 'Durante una sessione di studio il telefono…', ['Resta accanto con le notifiche', 'È lontano o silenziato per un tempo stabilito', 'Lo controllo spesso', 'Non cambia la concentrazione'], 1],
    ['monitoraggio', 'Se sbagli un esercizio…', ['Guardi subito la soluzione', 'Individui il tipo di errore e riprovi', 'Lo salti', 'Memorizzi il risultato'], 1],
    ['memoria', 'Per preparare un’interrogazione…', ['Rileggi dall’inizio alla fine', 'Prepari domande e provi una spiegazione senza appunti', 'Impari frasi a memoria', 'Ripeti solo la sera prima'], 1],
    ['elaborazione', 'Per collegare argomenti diversi…', ['Li tieni separati', 'Confronti cause, effetti, esempi e parole chiave', 'Sottolinei ogni riga', 'Aspetti che il collegamento venga da sé'], 1],
    ['comprensione', 'Quando non capisci una consegna…', ['Parti comunque', 'La riscrivi con parole tue e chiarisci il prodotto richiesto', 'Copi un esempio', 'Rinunci'], 1],
    ['memoria', 'Una sessione efficace termina con…', ['Un’altra rilettura', 'Un breve richiamo senza libro e il prossimo passo', 'Altre evidenziazioni', 'Nessuna verifica'], 1],
    ['monitoraggio', 'Per capire se un metodo funziona…', ['Conti solo il tempo trascorso', 'Controlli cosa sai fare senza aiuti e modifichi il piano', 'Aspetti il voto', 'Cambi metodo ogni giorno'], 1],
    ['attenzione', 'Quando la concentrazione cala…', ['Continui senza capire', 'Fai una pausa breve e riparti con un obiettivo preciso', 'Apri i social', 'Abbandoni la materia'], 1],
    ['elaborazione', 'Dopo aver studiato un concetto nuovo…', ['Lo lasci isolato', 'Crei un esempio tuo e spieghi dove può essere usato', 'Ricopi la definizione', 'Memorizzi solo le parole in grassetto'], 1],
    ['ambiente', 'Dove riesci più spesso a studiare?', ['In un posto sempre diverso, senza un piano', 'In un posto abbastanza stabile, preparato prima', 'Solo quando tutti gli altri hanno finito', 'Non ho mai osservato questa differenza'], 1],
    ['ambiente', 'Quando a casa arrivano rumori o interruzioni…', ['Abbandono subito il compito', 'Prevedo una soluzione: pausa, cuffie, altro spazio o avviso agli altri', 'Continuo anche se non capisco più', 'Aspetto che il problema sparisca'], 1],
    ['motivazione', 'Che cosa ti aiuta di più a iniziare?', ['Un voto o una pressione esterna', 'Un obiettivo concreto e il collegamento con qualcosa che mi interessa', 'Sapere che manca poco tempo', 'Una soluzione già pronta'], 1],
    ['motivazione', 'Quando un argomento diventa difficile…', ['Penso che non faccia per me', 'Cerco quale passaggio posso capire o provare per primo', 'Cambio subito materia', 'Aspetto che qualcuno lo risolva'], 1],
    ['aspettative', 'Che cosa vorresti ottenere da questo percorso?', ['Solo finire velocemente', 'Conoscere meglio come studio e portare via una strategia concreta', 'Una risposta uguale per tutti', 'Un voto senza dover provare'], 1],
    ['aspettative', 'Come capirai che il tuo metodo sta migliorando?', ['Quando studio più ore', 'Quando ricordo e so applicare ciò che ho studiato con meno aiuti', 'Quando il compito sembra più facile', 'Quando non commetto mai errori'], 1]
  ];

  const strategies = [
    { name: 'Richiamo attivo', summary: 'Ricostruisci ciò che sai senza guardare il materiale.', when: 'Dopo una prima comprensione e prima di una verifica.', steps: ['Studia un segmento breve', 'Chiudi o copri il materiale', 'Ricostruisci idee e passaggi', 'Riapri, controlla e correggi'], example: 'Dopo due pagine, scrivi cinque idee a memoria. Confronta con il testo e aggiungi in un altro colore ciò che mancava.', avoid: 'Rileggere mentre provi a ricordare: trasforma il richiamo in riconoscimento.', practice: 'Copri il testo e scrivi cinque idee essenziali; riaprilo e correggi in un altro colore.' },
    { name: 'Pratica distribuita', summary: 'Riprendi lo stesso contenuto in momenti separati invece di concentrarlo alla vigilia.', when: 'Per conoscenze che devono durare settimane o mesi.', steps: ['Prima comprensione oggi', 'Richiamo breve domani', 'Nuovo richiamo tra 3 giorni', 'Controllo finale dopo una settimana'], example: 'Crea quattro richiami da 8–10 minuti. Ogni volta parti senza libro e dedica più tempo a ciò che non emerge.', avoid: 'Ripetere identicamente: gli intervalli devono contenere richiamo e correzione.', practice: 'Crea ora tre appuntamenti di richiamo: domani, tra tre giorni e tra una settimana; scrivi cosa controllerai.' },
    { name: 'Alternanza degli esercizi', summary: 'Mescola problemi o argomenti collegati per imparare a scegliere la procedura.', when: 'Quando sai già svolgere almeno un esempio di ogni tipo.', steps: ['Seleziona 2–3 tipi collegati', 'Mescolali senza etichette', 'Scegli il metodo prima di agire', 'Spiega l’indizio che ti ha guidato'], example: 'Alterna causa/conseguenza, confronto e cronologia; per ogni domanda dichiara quale struttura userai e perché.', avoid: 'Alternare troppo presto, prima di avere capito i casi di base.', practice: 'Formula tre domande diverse sul testo: una di causa, una di confronto e una di applicazione; rispondi scegliendo il metodo.' },
    { name: 'Elaborazione', summary: 'Collega il nuovo a ciò che sai attraverso perché, esempi e conseguenze.', when: 'Quando vuoi comprendere relazioni, non soltanto definizioni.', steps: ['Individua l’idea centrale', 'Chiedi “perché è così?”', 'Crea un esempio personale', 'Collega a un concetto già noto'], example: 'Per ogni concetto completa: “Questo accade perché…”, “Un esempio è…”, “Si collega a…”.', avoid: 'Inventare collegamenti plausibili ma sbagliati: controllali sempre nel materiale.', practice: 'Rispondi per iscritto a tre domande: perché è importante, quale esempio nuovo puoi creare, a cosa già noto si collega.' },
    { name: 'Doppia codifica', summary: 'Combina parole e rappresentazioni visive che mostrano davvero le relazioni.', when: 'Per processi, strutture, sequenze e confronti.', steps: ['Seleziona massimo 5–7 idee', 'Scegli forma: flusso, mappa o confronto', 'Collega con frecce etichettate', 'Spiega il disegno senza leggere'], example: 'Trasforma il testo in quattro nodi collegati. Ogni freccia deve dire “causa”, “produce”, “contrasta” o un’altra relazione.', avoid: 'Decorare o ricopiare frasi intere: l’immagine deve aggiungere struttura.', practice: 'Crea una mini-mappa di massimo cinque nodi; usa frecce con parole-relazione e poi spiegala senza leggere.' },
    { name: 'Gestione dell’attenzione', summary: 'Prepara ambiente, obiettivo, durata e pausa prima di cominciare.', when: 'Quando inizi tardi, interrompi spesso o perdi il filo.', steps: ['Definisci un prodotto concreto', 'Allontana le distrazioni', 'Imposta un blocco breve', 'Chiudi con richiamo e prossimo passo'], example: 'Obiettivo: “ricostruire quattro idee”, 15 minuti, telefono fuori portata, una scheda aperta, pausa finale.', avoid: 'Misurare solo il tempo: il blocco deve terminare con un risultato osservabile.', practice: 'Scrivi un obiettivo verificabile, libera il piano di lavoro, silenzia il telefono e imposta un blocco di 12 minuti.' },
    { name: 'Autospiegazione', summary: 'Rendi esplicito perché compi un passaggio e come si collega al precedente.', when: 'Durante problemi, analisi di testi, procedure e dimostrazioni.', steps: ['Nomina il passaggio', 'Spiega perché serve', 'Collegalo a ciò che precede', 'Controlla se sapresti insegnarlo'], example: 'Dopo ogni paragrafo completa ad alta voce: “Qui l’autore dice…; serve perché…; si collega a…”.', avoid: 'Ripetere le stesse parole del testo senza esplicitare relazioni.', practice: 'Per ciascun paragrafo scrivi una frase che inizi con “Questo passaggio è importante perché…”.' },
    { name: 'Registro degli errori', summary: 'Trasforma l’errore in informazione su causa e prossima strategia.', when: 'Dopo esercizi, interrogazioni simulate e autocorrezioni.', steps: ['Descrivi l’errore preciso', 'Classifica la causa', 'Scrivi la correzione', 'Programma una nuova prova simile'], example: 'Tabella a tre colonne: errore (“confondo le cause”), causa (“lista senza relazioni”), rimedio (“mappa causale e richiamo domani”).', avoid: 'Scrivere soltanto “distrazione”: serve una causa su cui puoi intervenire.', practice: 'Dopo il test finale registra un errore o un’incertezza, la causa probabile e la prossima azione concreta.' }
  ];

  const samples = [
    { title: 'Storia · La stampa e la circolazione delle idee', label: 'Storia', focus: 'In che modo la stampa modificò produzione, controllo e diffusione delle idee in Europa?', text: ['A metà del Quattrocento la stampa a caratteri mobili rese più rapida la produzione dei libri. Prima, copiare un testo a mano richiedeva molto tempo e ogni esemplare poteva presentare differenze. Con caratteri riutilizzabili, carta e torchio, uno stesso testo poteva essere riprodotto in molte copie relativamente uniformi.', 'La maggiore disponibilità di libri non rese però tutti immediatamente lettori. Il costo diminuì, ma alfabetizzazione, lingua e accesso continuarono a creare differenze. Le botteghe tipografiche divennero luoghi in cui si incontravano artigiani, studiosi e commercianti; sceglievano quali opere pubblicare valutando interesse, rischi e possibilità di vendita.', 'La stampa accelerò la circolazione di idee religiose, scientifiche e politiche. Proprio per questo autorità civili e religiose tentarono di controllarla con privilegi, autorizzazioni e indici di opere proibite. La nuova tecnologia non produsse automaticamente libertà o verità: ampliò il pubblico e rese più veloce sia la diffusione delle conoscenze sia quella di errori e conflitti.'], prompts: ['Quali differenze introduce la stampa rispetto alla copia manuale?', 'Perché l’accesso ai libri rimase diseguale?', 'Qual è il rapporto tra maggiore circolazione e tentativi di controllo?'], model: 'Caratteri riutilizzabili e torchio aumentano velocità e uniformità delle copie. L’accesso resta diseguale per costi, alfabetizzazione e lingua. La circolazione più ampia delle idee aumenta il pubblico ma spinge le autorità a creare nuovi controlli.' },
    { title: 'Scienze · Effetto serra e cambiamento climatico', label: 'Scienze', focus: 'Perché l’effetto serra naturale è necessario, mentre il suo rafforzamento produce rischi?', text: ['La superficie terrestre riceve energia dal Sole e ne restituisce una parte sotto forma di radiazione infrarossa. Alcuni gas atmosferici, tra cui vapore acqueo, anidride carbonica e metano, assorbono e riemettono parte di questa energia. Questo effetto serra naturale mantiene temperature compatibili con la vita come la conosciamo.', 'Le attività umane modificano l’equilibrio aumentando la concentrazione di alcuni gas serra. Combustione di carbone, petrolio e gas, cambiamenti nell’uso del suolo, allevamenti e processi industriali contribuiscono in misura diversa. Più energia resta nel sistema climatico e cambiano temperature medie, precipitazioni, ghiacci ed eventi estremi.', 'Un singolo giorno freddo non smentisce il riscaldamento globale: il meteo descrive condizioni locali e di breve durata, il clima osserva andamenti su periodi lunghi e aree vaste. Le decisioni richiedono quindi serie di dati, modelli controllati e confronto tra molte evidenze, non un esempio isolato.'], prompts: ['Quale funzione svolge l’effetto serra naturale?', 'Quali attività rafforzano l’effetto serra?', 'Perché un episodio meteorologico non basta a descrivere il clima?'], model: 'L’effetto naturale trattiene energia e rende abitabile il pianeta. Le attività umane aumentano gas come CO₂ e metano. Il meteo riguarda eventi brevi e locali, mentre il clima emerge da serie lunghe e vaste di osservazioni.' },
    { title: 'Progettazione · Dal bozzetto al prototipo', label: 'Area artistico-professionale', focus: 'Perché il prototipo non è una copia imperfetta del prodotto finale, ma uno strumento per decidere?', text: ['Un bozzetto rende visibile un’idea iniziale: proporzioni, ritmo, materiali, funzione e atmosfera. Non deve risolvere ogni dettaglio. Serve soprattutto a generare alternative rapidamente e a rendere discutibili scelte che, finché restano soltanto nella mente, sono difficili da confrontare.', 'Il prototipo traduce alcune di quelle scelte in una forma che può essere osservata o provata. Può essere una maquette, un campione, una sequenza grafica, una registrazione di prova o una simulazione digitale. La sua fedeltà dipende dalla domanda: se bisogna controllare una proporzione non è necessario rifinire la superficie; se si valuta il timbro, invece, il materiale può diventare decisivo.', 'Provare presto riduce il costo degli errori e produce informazioni. Il feedback è utile quando riguarda criteri dichiarati — funzione, leggibilità, equilibrio, resistenza, espressività — e conduce a una modifica verificabile. Documentare versioni e decisioni permette di distinguere un cambiamento casuale da un miglioramento motivato.'], prompts: ['Che funzione ha il bozzetto?', 'Da che cosa dipende la fedeltà del prototipo?', 'Quando un feedback produce un miglioramento verificabile?'], model: 'Il bozzetto genera e confronta alternative. Il livello di fedeltà dipende dalla domanda da verificare. Il feedback è utile quando usa criteri dichiarati e porta a una modifica controllabile e documentata.' }
  ];

  const visualMaps = {
    'Storia': { title: 'Mappa causale · la stampa', nodes: ['Caratteri mobili + torchio', 'Più copie e maggiore uniformità', 'Accesso ancora diseguale', 'Circolazione più rapida', 'Nuovi controlli e conflitti'], links: ['produce', 'ma non elimina', 'permette', 'spinge a'] },
    'Scienze': { title: 'Schema processo · effetto serra', nodes: ['Energia dal Sole', 'Radiazione infrarossa', 'Gas serra naturali', 'Equilibrio climatico', 'Attività umane → aumento gas'], links: ['si trasforma in', 'viene assorbita da', 'mantengono', 'si altera con'] },
    'Area artistico-professionale': { title: 'Mappa di progetto · dal bozzetto al prototipo', nodes: ['Idea e alternative', 'Bozzetto: rendere visibile', 'Prototipo: provare una scelta', 'Feedback su criteri', 'Modifica documentata'], links: ['si chiarisce nel', 'si verifica nel', 'si valuta con', 'porta a'] }
  };
  const profileActivities = {
    professionali: {
      1: { level: 'Guidato passo passo · 1ª professionale', title: 'Storia · Vivere lungo il Nilo', label: 'Storia', focus: 'Perché il Nilo era importante e che cosa dovevano fare gli Egizi per usare bene le sue acque?', text: ['Più di quattromila anni fa, molti Egizi vivevano vicino al Nilo. Intorno c’erano zone desertiche, mentre il fiume offriva acqua per bere, lavarsi e coltivare. Per questo villaggi e campi si trovavano soprattutto lungo le sue rive.', 'Ogni anno le acque del Nilo crescevano e coprivano una parte dei terreni. Quando si ritiravano, lasciavano sul suolo un fango scuro che rendeva la terra fertile. I contadini potevano così seminare grano, orzo, legumi e lino.', 'Prima della semina, gli abitanti pulivano i canali che portavano l’acqua nei campi e controllavano i piccoli argini. Questo lavoro richiedeva tempo e collaborazione: se un canale era bloccato o un argine si rompeva, più famiglie potevano perdere il raccolto.', 'Dopo la raccolta, una parte dei cereali veniva conservata nei magazzini. Gli scribi registravano le quantità, mentre artigiani e operai preparavano strumenti, ceste e contenitori. Il Nilo offriva risorse importanti, ma erano il lavoro e l’organizzazione delle persone a trasformarle in cibo e sicurezza.'], prompts: ['Dove sorgevano molti villaggi egizi e perché?', 'Che cosa lasciava il Nilo sui campi dopo il ritiro delle acque? Perché era utile?', 'Metti in ordine queste azioni: conservare il raccolto, pulire i canali, ritiro delle acque, seminare.', 'Perché la cura di canali e argini richiedeva la collaborazione di più persone?', 'Spiega la frase finale: “Il Nilo offriva risorse, ma servivano lavoro e organizzazione”. Usa almeno due informazioni del testo.'], model: 'Molti villaggi sorgevano lungo il Nilo perché il fiume dava acqua e permetteva di coltivare in una zona in gran parte desertica. Dopo il ritiro, le acque lasciavano un fango fertile. L’ordine è: ritiro delle acque, pulizia e cura dei canali, semina, conservazione del raccolto. Canali e argini servivano i campi di più famiglie, quindi richiedevano un lavoro comune. Il fiume forniva acqua e terra fertile, ma gli Egizi dovevano curare i canali, coltivare, conservare i cereali e registrare le quantità.', map: { title: 'Dal Nilo al raccolto', nodes: ['Crescita delle acque', 'Fango fertile sui campi', 'Canali e argini', 'Semina e raccolto', 'Cereali conservati'], links: ['lascia', 'l’acqua passa nei', 'permettono', 'poi'] } },
      2: { level: 'Guidato · 2ª professionale', title: 'Laboratorio · Preparare una macedonia', label: 'Testo pratico', focus: 'Quali azioni permettono al gruppo di lavorare con ordine?', text: ['Martina entra nel laboratorio di cucina. Indossa il grembiule e lava con cura le mani.', 'Con il gruppo prepara gli ingredienti, ascolta la consegna e taglia la frutta con attenzione.', 'Alla fine pulisce il tavolo e rimette gli strumenti al loro posto. Il lavoro riesce perché ogni passaggio è fatto con ordine.'], prompts: ['Qual è la prima azione di Martina?', 'Che cosa fa durante il lavoro?', 'Perché il lavoro riesce?'], model: 'Martina prima indossa il grembiule e lava le mani. Durante il lavoro ascolta, prepara e taglia la frutta. Il lavoro riesce perché il gruppo segue i passaggi e riordina.', map: { title: 'Sequenza di lavoro', nodes: ['Prepararsi', 'Ascoltare la consegna', 'Lavorare con attenzione', 'Pulire e riordinare'], links: ['poi', 'poi', 'infine'] } },
      3: { level: 'Base · 3ª professionale', title: 'Cittadinanza · Bicchieri riutilizzabili', label: 'Avviso', focus: 'Quale cambiamento propone l’avviso e perché?', text: ['Da lunedì 14 ottobre il punto ristoro della scuola userà bicchieri riutilizzabili.', 'Per ricevere il bicchiere si lascia una cauzione di 1 euro, restituita quando lo si riconsegna pulito entro la giornata.', 'La scelta riduce i rifiuti e aiuta a mantenere ordinati gli spazi comuni.'], prompts: ['Quando inizia la novità?', 'Che cosa bisogna fare per riavere la cauzione?', 'Qual è lo scopo della scelta?'], model: 'La novità inizia lunedì 14 ottobre. Il bicchiere va restituito pulito entro la giornata. Lo scopo è ridurre i rifiuti e avere spazi più ordinati.', map: { title: 'Avviso: informazione e scopo', nodes: ['Nuovi bicchieri', 'Cauzione di 1 euro', 'Restituzione pulita', 'Meno rifiuti'], links: ['richiede', 'si recupera con', 'produce'] } },
      4: { level: 'Intermedio · 4ª professionale', title: 'Comunicazione · Un problema in biblioteca', label: 'Testo funzionale', focus: 'Come trasformare un problema osservato in una richiesta cortese?', text: ['Nella biblioteca scolastica, nelle ultime due settimane, tre computer non si sono avviati correttamente.', 'Gli studenti hanno dovuto cambiare postazione più volte e alcune ricerche sono iniziate in ritardo.', 'Sarebbe utile controllare le apparecchiature e comunicare i tempi di riparazione.'], prompts: ['Quali fatti verificabili presenta il testo?', 'Quale conseguenza hanno avuto i guasti?', 'Quale richiesta viene proposta?'], model: 'I fatti sono che tre computer non si avviano da due settimane. Gli studenti cambiano postazione e iniziano tardi le ricerche. La richiesta è controllare i computer e comunicare i tempi di riparazione.', map: { title: 'Dal fatto alla richiesta', nodes: ['Tre computer guasti', 'Postazioni cambiate', 'Ricerche in ritardo', 'Controllo e comunicazione'], links: ['causa', 'produce', 'richiede'] } },
      5: { level: 'Autonomo · 5ª professionale', title: 'Orientamento · Presentarsi a un colloquio', label: 'Testo argomentativo', focus: 'Quali elementi rendono efficace una presentazione professionale?', text: ['Un colloquio efficace non è un elenco di esperienze. Richiede di scegliere ciò che dimostra competenze, affidabilità e desiderio di imparare.', 'È utile preparare esempi concreti: un progetto svolto, un problema risolto, un’attività di gruppo.', 'Anche una domanda finale sull’azienda mostra interesse e consapevolezza.'], prompts: ['Qual è la tesi del testo?', 'Quali esempi possono dimostrare una competenza?', 'Perché una domanda finale è utile?'], model: 'La tesi è che una buona presentazione seleziona informazioni significative. Progetti, problemi risolti e lavori di gruppo sono esempi concreti. Una domanda finale mostra interesse per l’azienda.', map: { title: 'Presentazione professionale', nodes: ['Competenze selezionate', 'Esempio concreto', 'Affidabilità', 'Domanda finale', 'Interesse per l’azienda'], links: ['si dimostrano con', 'rafforza', 'mostra', 'comunica'] } }
    },
    tecnici: {
      1: { level: 'Guidato · 1ª tecnico', title: 'Tecnologia · Il ponte di cartone', label: 'Racconto di laboratorio', focus: 'Quale problema incontrano Luca e Sara? Come lo risolvono?', text: ['Luca trova sul banco cartone, una lente e un foglio di istruzioni. Con Sara costruisce un piccolo ponte.', 'All’inizio una parte cade. I due controllano i passaggi e rinforzano la base.', 'Alla fine il ponte sostiene tutti i pesetti della prova.'], prompts: ['Che cosa costruiscono?', 'Quale problema incontrano?', 'Quale soluzione trovano?'], model: 'Luca e Sara costruiscono un piccolo ponte. Una parte cade. Controllano le istruzioni e rinforzano la base.', map: { title: 'Problema e soluzione', nodes: ['Costruire il ponte', 'Una parte cade', 'Controllare i passaggi', 'Rinforzare la base', 'Prova riuscita'], links: ['ma', 'allora', 'per', 'porta a'] } },
      2: { level: 'Guidato · 2ª tecnico', title: 'Scienze · Non sprecare acqua', label: 'Testo espositivo', focus: 'Quali gesti riducono lo spreco di acqua?', text: ['L’acqua potabile non è una risorsa infinita. In casa serve per lavarsi, cucinare e pulire.', 'Piccoli gesti limitano lo spreco: chiudere il rubinetto mentre ci si lava i denti, riparare una perdita, usare la lavatrice a pieno carico.', 'Ridurre gli sprechi significa proteggere una risorsa necessaria a tutti.'], prompts: ['Qual è l’argomento del testo?', 'Indica due gesti utili.', 'Perché è importante risparmiare acqua?'], model: 'Il testo parla del risparmio dell’acqua. Due gesti sono chiudere il rubinetto e riparare le perdite. È importante perché l’acqua potabile è una risorsa necessaria e non infinita.', map: { title: 'Risparmiare acqua', nodes: ['Acqua potabile', 'Non è infinita', 'Gesti quotidiani', 'Meno sprechi', 'Risorsa protetta'], links: ['quindi', 'richiede', 'producono', 'per'] } },
      3: { level: 'Intermedio · 3ª tecnico', title: 'Laboratorio · Misurare una temperatura', label: 'Procedura tecnica', focus: 'Quali condizioni rendono affidabile una misurazione?', text: ['Per verificare una temperatura ambiente, posiziona il termometro lontano da finestre e fonti di calore.', 'Attendi cinque minuti senza spostarlo. Leggi il valore all’altezza degli occhi.', 'Annota data, ora, luogo e temperatura: una misurazione affidabile richiede condizioni costanti.'], prompts: ['Dove non va posizionato il termometro?', 'Quali dati vanno annotati?', 'Perché le condizioni devono restare costanti?'], model: 'Il termometro non va vicino a finestre o fonti di calore. Vanno annotati data, ora, luogo e temperatura. Le condizioni costanti permettono una misurazione confrontabile e affidabile.', map: { title: 'Misurazione affidabile', nodes: ['Posizione corretta', 'Attesa di 5 minuti', 'Lettura corretta', 'Dati annotati', 'Risultato confrontabile'], links: ['poi', 'poi', 'e', 'produce'] } },
      4: { level: 'Intermedio-avanzato · 4ª tecnico', title: 'Dati · Consumo elettrico dell’aula', label: 'Lettura di dati', focus: 'Che cosa spiegano le differenze di consumo durante la settimana?', text: ['Consumo elettrico: lunedì 12 kWh, martedì 14, mercoledì 10, giovedì 16, venerdì 11.', 'Giovedì si è svolto un laboratorio con computer accesi per quattro ore. Mercoledì l’aula è stata usata solo al mattino.', 'I dati vanno letti insieme alle condizioni in cui sono stati raccolti.'], prompts: ['Quale giorno registra il massimo consumo?', 'Quale informazione spiega il dato di giovedì?', 'Perché non basta leggere i numeri isolatamente?'], model: 'Il massimo è giovedì con 16 kWh. Il laboratorio con computer accesi spiega il valore elevato. I dati vanno collegati alle condizioni di utilizzo per poterli interpretare.', map: { title: 'Dato e contesto', nodes: ['Consumi settimanali', 'Giovedì: 16 kWh', 'Laboratorio con computer', 'Mercoledì: 10 kWh', 'Uso solo al mattino'], links: ['mostrano', 'spiegato da', 'confronto con', 'spiegato da'] } },
      5: { level: 'Avanzato · 5ª tecnico', title: 'Decisione tecnica · Illuminazione a scuola', label: 'Testo argomentativo', focus: 'Quali criteri servono per scegliere tra lampade LED e riduzione dell’orario?', text: ['La scuola può sostituire le lampade con LED oppure ridurre l’orario di illuminazione nei corridoi.', 'I LED richiedono un investimento iniziale, ma consumano meno e durano più a lungo. Ridurre l’orario costa meno subito, ma può diminuire comfort e sicurezza.', 'Una scelta responsabile considera costi, benefici, ambiente e persone coinvolte.'], prompts: ['Quali sono le due opzioni?', 'Quale limite hanno i LED? Quale la riduzione dell’orario?', 'Quali criteri propone il testo?'], model: 'Le opzioni sono installare LED o ridurre l’orario. I LED costano all’inizio; ridurre l’orario può diminuire comfort e sicurezza. I criteri sono costi, benefici, ambiente e persone coinvolte.', map: { title: 'Valutare una scelta tecnica', nodes: ['Due opzioni', 'Costi iniziali', 'Consumi e durata', 'Comfort e sicurezza', 'Decisione responsabile'], links: ['si valutano con', 'confrontati con', 'insieme a', 'orientano'] } }
    },
    licei: {
      1: { level: 'Guidato · 1ª liceo', title: 'Mito · Il fuoco di Prometeo', label: 'Mito', focus: 'Quale dono porta Prometeo agli uomini e che cosa cambia?', text: ['Prometeo vide gli uomini vivere al freddo e nel buio. Per aiutarli rubò una scintilla del fuoco divino.', 'Quando gli uomini ricevettero il fuoco, impararono a costruire, a cuocere il cibo e a riunirsi.', 'Zeus si adirò, ma il dono di Prometeo cambiò per sempre la vita degli uomini.'], prompts: ['Quale problema vede Prometeo?', 'Che cosa dona agli uomini?', 'Che cosa può rappresentare il fuoco?'], model: 'Prometeo vede gli uomini nel freddo e nel buio. Dona loro il fuoco. Il fuoco può rappresentare conoscenza, tecnica e progresso.', map: { title: 'Il dono di Prometeo', nodes: ['Uomini nel buio', 'Prometeo interviene', 'Dono del fuoco', 'Nuove capacità', 'Vita trasformata'], links: ['spinge', 'porta a', 'permette', 'cambia'] } },
      2: { level: 'Intermedio · 2ª liceo', title: 'Storia · Pompei e la memoria', label: 'Testo storico', focus: 'Perché Pompei è insieme luogo di catastrofe e fonte storica?', text: ['Nel 79 d.C. l’eruzione del Vesuvio coprì Pompei di cenere e lapilli. Molti abitanti fuggirono o cercarono rifugio.', 'Secoli dopo, gli scavi riportarono alla luce case, affreschi, oggetti e tracce della vita quotidiana.', 'Pompei non è soltanto il luogo di una catastrofe: è anche una testimonianza di una città romana fermata in un istante.'], prompts: ['Indica due fatti storici.', 'Quali fonti materiali trovano gli archeologi?', 'Che cosa significa “fermata in un istante”?'], model: 'L’eruzione avviene nel 79 d.C. e gli scavi riportano alla luce la città. Le fonti sono case, affreschi e oggetti. La frase indica che Pompei conserva tracce di un preciso momento della vita romana.', map: { title: 'Pompei: evento e fonte', nodes: ['Eruzione del Vesuvio', 'Città sepolta', 'Scavi archeologici', 'Oggetti e case', 'Conoscenza della vita romana'], links: ['produce', 'permette', 'restituiscono', 'diventano'] } },
      3: { level: 'Intermedio-avanzato · 3ª liceo', title: 'Lettura · Perché leggere narrativa', label: 'Testo argomentativo', focus: 'Quale tesi sostiene il testo sul valore della narrativa?', text: ['Leggere narrativa non serve soltanto a conoscere storie inventate. Seguendo un personaggio, proviamo a capire paure, scelte e conseguenze.', 'Questo esercizio può rendere più attenti alla complessità delle persone reali.', 'Un romanzo non sostituisce l’esperienza diretta, ma offre uno spazio sicuro per interrogarsi su punti di vista diversi dal proprio.'], prompts: ['Formula la tesi dell’autore.', 'Quale argomento sostiene la tesi?', 'Quale limite riconosce il testo?'], model: 'La tesi è che la narrativa aiuta a comprendere la complessità delle persone. L’argomento è che seguire paure e scelte dei personaggi allena a considerare altri punti di vista. Il limite è che non sostituisce l’esperienza diretta.', map: { title: 'Struttura dell’argomentazione', nodes: ['Tesi: valore della narrativa', 'Personaggi e scelte', 'Punti di vista diversi', 'Limite riconosciuto', 'Esperienza diretta'], links: ['si sostiene con', 'favoriscono', 'ma non sostituisce', 'resta necessaria'] } },
      4: { level: 'Avanzato · 4ª liceo', title: 'Poesia · La sera in città', label: 'Testo poetico', focus: 'Come cambia l’atmosfera della città nel testo?', text: ['La sera posa una mano lenta sui tetti stanchi della città; una finestra accesa resiste, piccola vela nell’oscurità.', 'Nella strada il rumore si scioglie, resta un passo, poi niente più.', 'Forse il silenzio non è assenza: è una voce che ascolta di più.'], prompts: ['Individua una personificazione.', 'Quale immagine è una metafora?', 'Come interpreti gli ultimi due versi?'], model: 'La personificazione è “la sera posa una mano”. La finestra è una “piccola vela”, una metafora. Il silenzio non è vuoto: diventa una condizione di ascolto più profondo.', map: { title: 'Dal rumore al silenzio', nodes: ['Sera sulla città', 'Finestra accesa', 'Rumore che si scioglie', 'Silenzio', 'Ascolto più profondo'], links: ['illumina', 'lascia spazio a', 'diventa', 'suggerisce'] } },
      5: { level: 'Avanzato · 5ª liceo', title: 'Fonti · Informazioni e pensiero critico', label: 'Saggio breve', focus: 'Perché l’accesso alle informazioni richiede competenze di verifica?', text: ['Fonte A: la tecnologia rende immediato l’accesso alle informazioni, ma non garantisce la capacità di valutarle.', 'Fonte B: verificare una fonte significa chiedersi chi parla, con quale competenza, per quale scopo e con quali prove.', 'Fonte C: la velocità della condivisione può trasformare un errore in una convinzione diffusa.'], prompts: ['Quale questione comune emerge dalle fonti?', 'Quale criterio di verifica indica la fonte B?', 'Quale rischio evidenzia la fonte C?'], model: 'Le fonti trattano dell’uso critico delle informazioni digitali. La fonte B invita a verificare autore, competenza, scopo e prove. La fonte C avverte che un errore condiviso velocemente può diventare credibile per molti.', map: { title: 'Informazione e verifica', nodes: ['Accesso immediato', 'Valutazione necessaria', 'Autore, scopo, prove', 'Condivisione veloce', 'Rischio di errore diffuso'], links: ['non garantisce', 'richiede', 'si confronta con', 'può produrre'] } }
    }
  };
  const beginnerQuestions = [
    ['pianificazione', 'Quando ricevi un compito lungo…', ['Cominci dalla parte che sembra più facile', 'Leggi che cosa devi ottenere e dividi il lavoro in passaggi', 'Aspetti di avere molto tempo libero', 'Chiedi subito a un compagno che cosa ha fatto'], 1],
    ['pianificazione', 'Prima di iniziare a studiare un testo…', ['Leggi subito tutto senza fermarti', 'Prepari molti materiali anche se non servono', 'Scrivi una domanda a cui vuoi saper rispondere alla fine', 'Sottolinei il titolo e poi continui'], 2],
    ['attenzione', 'Se il telefono ti interrompe mentre studi…', ['Lo silenzi e lo metti fuori portata per un tempo deciso', 'Rispondi velocemente e poi riprendi', 'Lo lasci acceso per controllare l’ora', 'Cambi attività ogni volta che arriva un messaggio'], 0],
    ['attenzione', 'Quando perdi il filo durante la lettura…', ['Continui fino alla fine anche se non capisci', 'Sottolinei più frasi possibili', 'Passi direttamente alle domande', 'Ti fermi, rileggi l’ultimo passaggio chiaro e riparti'], 3],
    ['comprensione', 'Quando una consegna contiene più richieste…', ['Ne scegli una e inizi', 'Cerchi i verbi della consegna e li trasformi in una lista di azioni', 'Leggi soltanto l’esempio', 'Aspetti che qualcuno la spieghi'], 1],
    ['comprensione', 'Se nel testo trovi una parola importante che non conosci…', ['La salti e provi a indovinare tutto il resto', 'Copi la parola senza cercarla', 'Usi la frase per formulare un’ipotesi, poi controlli il significato', 'Interrompi il lavoro'], 2],
    ['memoria', 'Dopo aver letto due paragrafi…', ['Copri il testo, ricostruisci le idee principali e poi controlli', 'Li rileggi subito nello stesso modo', 'Tieni il testo aperto mentre ripeti', 'Copi le frasi che sembrano più lunghe'], 0],
    ['memoria', 'Per ricordare l’ordine di fatti o fasi…', ['Impari a memoria la prima frase', 'Rileggi soltanto il finale', 'Disegni senza indicare i collegamenti', 'Scrivi i passaggi essenziali e li colleghi con prima, perché, poi e quindi'], 3],
    ['monitoraggio', 'Quando la tua risposta è diversa dal modello…', ['La cancelli e copi il modello', 'Pensi che sia comunque sbagliata', 'Controlli che cosa manca, correggi e spieghi l’errore', 'Leggi il modello senza tornare alla tua risposta'], 2],
    ['monitoraggio', 'Alla fine di una sessione di studio…', ['Chiudi tutto appena finisce il tempo', 'Verifichi che cosa sai fare senza aiuti e decidi il prossimo passo', 'Conti quante pagine hai letto', 'Riparti dall’inizio per sicurezza'], 1]
  ];
  const beginnerStrategies = [
    { name: 'Dividi in passaggi', summary: 'Trasforma un compito lungo in azioni brevi e visibili.', when: 'Quando non sai da dove iniziare o temi di non finire.', steps: ['Leggi il risultato richiesto', 'Scrivi i passaggi', 'Parti dal primo', 'Spunta e controlla'], example: 'Per il testo di storia: capisco la domanda, leggo, chiarisco le parole, collego i fatti, rispondo.', avoid: 'Scrivere una lista troppo lunga o iniziare da un punto casuale.', practice: 'Scrivi in quattro passaggi come affronterai il brano, poi spunta ogni passaggio concluso.' },
    { name: 'Richiamo e controllo', summary: 'Prova a ricordare senza guardare, poi correggi ciò che manca.', when: 'Dopo una parte breve di testo o prima di una verifica.', steps: ['Leggi una parte', 'Copri il testo', 'Ricostruisci le idee', 'Riapri e correggi'], example: 'Dopo due paragrafi, racconta i fatti principali senza leggere. Poi aggiungi in un altro colore ciò che avevi dimenticato.', avoid: 'Tenere il testo aperto: in quel caso stai riconoscendo, non ricordando.', practice: 'Copri il testo e scrivi quattro informazioni importanti; riaprilo e completa in un altro colore.' },
    { name: 'Catena di cause e azioni', summary: 'Collega i fatti per capire ordine, cause e conseguenze.', when: 'Con racconti, procedure e spiegazioni che hanno più fasi.', steps: ['Scegli i fatti essenziali', 'Mettili in ordine', 'Aggiungi parole-legame', 'Spiega seguendo le frecce'], example: 'Il Nilo si ritira → lascia il fango fertile → i contadini possono seminare.', avoid: 'Copiare frasi intere senza spiegare il legame tra un fatto e l’altro.', practice: 'Crea una catena di cinque fatti e usa almeno una volta “perché” e una volta “quindi”.' },
    { name: 'Errore utile', summary: 'Usa l’errore per capire quale passaggio cambiare.', when: 'Dopo una risposta, un esercizio o un confronto con un modello.', steps: ['Individua la differenza', 'Spiega la causa', 'Correggi', 'Riprova senza aiuto'], example: 'Ho confuso causa e conseguenza perché ho guardato solo l’ordine. Aggiungo “perché” e provo di nuovo.', avoid: 'Limitarsi a copiare la soluzione o scrivere soltanto “distrazione”.', practice: 'Dopo il confronto, annota una cosa mancante, il motivo e la correzione che farai.' }
  ];
  const standardQuestions = questions.map(question => [question[0], question[1], [...question[2]], question[3]]);
  const isBeginnerProfile = () => state.school === 'professionali' && state.year === '1';
  const currentSample = () => profileActivities[state.school][state.year];
  const currentStrategyLibrary = () => isBeginnerProfile() ? beginnerStrategies : strategies;
  function renderStudyMap(sample) {
    const map = sample.map || visualMaps[sample.label];
    return `<section class="study-maps" aria-labelledby="map-title"><div class="study-map-head"><div><div class="kicker">Esempio sul brano</div><h4 id="map-title">${map.title}</h4></div><span>Osserva le relazioni, non copiare le frasi</span></div><div class="map-flow">${map.nodes.map((node, index) => `<div class="map-node"><span>${String(index + 1).padStart(2, '0')}</span><b>${node}</b>${index < map.links.length ? `<small>${map.links[index]}</small>` : ''}</div>`).join('')}</div><div class="map-note"><strong>Come leggerla.</strong> Le frecce rispondono alla domanda-guida: ogni nodo è breve, ogni relazione dice che cosa cambia o dipende da che cosa. Ora prova a costruire una versione tua con massimo 5–7 nodi.</div></section>`;
  }
  const state = { step: 0, answers: [], chosen: [], exercise: [], reflection: '', sample: 0, recall: '', reveal: false, year: '1', school: 'professionali' };
  function applyProfile() {
    state.year = '1';
    const selectedQuestions = isBeginnerProfile() ? beginnerQuestions : state.school === 'tecnici' ? standardQuestions.slice(0, 10) : standardQuestions.slice(0, 14);
    questions.splice(0, questions.length, ...selectedQuestions.map(question => [question[0], question[1], [...question[2]], question[3]]));
    samples.splice(0, samples.length, currentSample());
    state.sample = 0;
  }
  function renderProfileChooser() {
    return `<section class="study-profile study-profile-single" aria-label="Scegli il percorso di prima"><h4>Scegli il tuo percorso</h4><p>Per ora il laboratorio è dedicato alle classi prime, con tre livelli di guida.</p><label for="studySchool">Classe prima<select id="studySchool" data-study-profile><option value="professionali" ${state.school === 'professionali' ? 'selected' : ''}>1ª professionale · molto guidato</option><option value="tecnici" ${state.school === 'tecnici' ? 'selected' : ''}>1ª tecnico · guidato</option><option value="licei" ${state.school === 'licei' ? 'selected' : ''}>1ª liceo · guidato avanzato</option></select></label></section>`;
  }
  applyProfile();
  const content = document.getElementById('studyContent');
  const button = (label, action, disabled = false, secondary = false) => `<button class="btn ${secondary ? 'secondary' : ''}" data-study-action="${action}" ${disabled ? 'disabled' : ''}>${label}</button>`;
  const exerciseCheck = (index, label) => `<label class="guided-check"><input type="checkbox" name="study-exercise${index}" ${state.exercise[index] ? 'checked' : ''}><span>${label}</span></label>`;

  function updateSteps() {
    const easySteps = [['1 · Come studio', '8 min'], ['2 · Diagnosi', '5 min'], ['3 · Strategie', '8 min'], ['4 · Egizi', '25 min'], ['5 · Piano', '6 min']];
    const technicalSteps = [['1 · Come studio', '10 min'], ['2 · Diagnosi', '7 min'], ['3 · Strategie', '15 min'], ['4 · Prova', '20 min'], ['5 · Piano', '5 min']];
    const liceoSteps = [['1 · Autoplacement', '12 min'], ['2 · Diagnosi', '8 min'], ['3 · Strategie', '15–20 min'], ['4 · Prova', '20 min'], ['5 · Piano', '8 min']];
    const labels = isBeginnerProfile() ? easySteps : state.school === 'tecnici' ? technicalSteps : liceoSteps;
    document.querySelectorAll('.study-step').forEach((step, index) => {
      step.classList.toggle('active', index === state.step);
      step.innerHTML = `${labels[index][0]} <small>${labels[index][1]}</small>`;
    });
    const sectionKicker = document.querySelector('#tab-studio .section-head .kicker');
    if (sectionKicker) sectionKicker.textContent = isBeginnerProfile() ? '01 · circa 50 minuti' : state.school === 'tecnici' ? '01 · circa 55 minuti' : '01 · circa 65 minuti';
    const sectionLead = document.querySelector('#tab-studio .section-head .lead');
    if (sectionLead && document.body.dataset.profile !== 'docente') sectionLead.textContent = isBeginnerProfile() ? 'Osserva come affronti un compito, scegli due strategie e provale passo passo con un testo di storia sugli Egizi.' : 'Osserva le tue abitudini, scopri punti di forza e fragilità, prova strategie efficaci e costruisci un piano personale.';
    const researchNote = document.querySelector('#tab-studio .study-research');
    if (researchNote) researchNote.innerHTML = isBeginnerProfile() ? '<strong>Che cosa provi.</strong> Pianificare, leggere in modo attivo, ricostruire senza guardare, collegare cause e conseguenze e correggere un errore.' : '<strong>Su quali evidenze si basa.</strong> Richiamo attivo, pratica distribuita, alternanza degli esercizi, elaborazione, doppia codifica e monitoraggio metacognitivo.';
  }

  function render() {
    updateSteps();
    if (state.step === 0) {
      const questionGroups = isBeginnerProfile()
        ? [['Prima e durante il compito', questions.slice(0, 6)], ['Ricordo e controllo', questions.slice(6, 10)]]
        : state.school === 'tecnici'
          ? [['Come organizzo lo studio', questions.slice(0, 8)], ['Come controllo il lavoro', questions.slice(8, 10)]]
          : [['Abitudini di studio', questions.slice(0, 12)], ['Ambiente domestico', questions.slice(12, 14)]];
      let questionIndex = 0;
      const time = isBeginnerProfile() ? '8 minuti' : state.school === 'tecnici' ? '10 minuti' : '12 minuti';
      const stageTitle = isBeginnerProfile() ? '1. Come studio oggi?' : '1. Autoplacement: come studi oggi?';
      const stageIntro = isBeginnerProfile() ? 'Scegli ciò che fai davvero, non ciò che pensi sia giusto. Il risultato serve a capire quale passaggio allenare: non è un voto.' : 'Rispondi sulle tue abitudini reali, sull’ambiente in cui studi e su ciò che ti motiva. Non ci sono risposte giuste o sbagliate: servono a costruire un percorso utile per te.';
      const diagnoseLabel = isBeginnerProfile() ? 'Guarda il risultato' : 'Calcola la mia mappa';
      content.innerHTML = `${renderProfileChooser()}<h3>${stageTitle}</h3><p>${stageIntro} Tempo previsto: ${time}.</p>${questionGroups.map(([title, group]) => `<section class="study-question-group"><h4>${title}</h4>${group.map(question => { const index = questionIndex++; return `<div class="study-question"><p>${index + 1}. ${question[1]}</p>${question[2].map((option, optionIndex) => `<label class="study-option"><input type="radio" name="study-q${index}" value="${optionIndex}" ${state.answers[index] === optionIndex ? 'checked' : ''}><span>${option}</span></label>`).join('')}</div>`; }).join('')}</section>`).join('')}<div class="study-actions">${button(diagnoseLabel, 'diagnose')}</div>`;
    } else if (state.step === 1) {
      const areaNames = isBeginnerProfile()
        ? { pianificazione: 'Organizzare i passaggi', attenzione: 'Proteggere l’attenzione', memoria: 'Ricordare senza guardare', comprensione: 'Capire testo e consegna', monitoraggio: 'Controllare e correggere' }
        : { pianificazione: 'Pianificazione', memoria: 'Memoria e richiamo', attenzione: 'Gestione dell’attenzione', monitoraggio: 'Controllo del metodo', elaborazione: 'Elaborazione e collegamenti', comprensione: 'Comprensione della consegna', ambiente: 'Ambiente domestico', motivazione: 'Motivazione', aspettative: 'Aspettative personali' };
      const scores = {};
      questions.forEach((question, index) => {
        const area = question[0];
        scores[area] ||= [];
        scores[area].push(state.answers[index] === question[3] ? 3 : 1);
      });
      const rows = Object.entries(scores).map(([area, values]) => [areaNames[area], values.reduce((a, b) => a + b, 0) / values.length]);
      const strongest = [...rows].sort((a, b) => b[1] - a[1])[0][0];
      const weakest = [...rows].sort((a, b) => a[1] - b[1])[0][0];
      if (isBeginnerProfile()) {
        const uniformProfile = rows.every(([, score]) => score === rows[0][1]);
        const summary = uniformProfile ? '<strong>Profilo uniforme:</strong> le cinque aree sono allo stesso livello. Nella prova puoi sceglierne due da rendere più stabili.' : `<strong>Punto già presente:</strong> ${strongest}. <strong>Passaggio da allenare:</strong> ${weakest}.`;
        content.innerHTML = `<h3>2. La tua mappa di partenza</h3><p>${summary} Il risultato descrive abitudini che possono cambiare: non è un giudizio sulle tue capacità.</p>${rows.map(([name, score]) => `<div class="study-card"><h4>${name} · ${score < 1.6 ? 'da allenare' : score < 2.6 ? 'in costruzione' : 'già presente'}</h4><div class="progress"><i style="width:${Math.round(score / 3 * 100)}%"></i></div></div>`).join('')}<div class="study-actions">${button('Rivedi le risposte', 'back', false, true)}${button('Scegli due strategie', 'strategies')}</div>`;
      } else {
        content.innerHTML = `<h3>2. La tua mappa</h3><p><strong>Punto di forza:</strong> ${strongest}. <strong>Area da allenare:</strong> ${weakest}. Il profilo descrive abitudini modificabili, non capacità fisse.</p>${rows.map(([name, score]) => `<div class="study-card"><h4>${name} · ${score < 1.6 ? 'da allenare' : score < 2.6 ? 'in costruzione' : 'punto di forza'}</h4><div class="progress"><i style="width:${Math.round(score / 3 * 100)}%"></i></div></div>`).join('')}<div class="study-actions">${button('Rivedi le risposte', 'back', false, true)}${button('Conosci le strategie', 'strategies')}</div>`;
      }
    } else if (state.step === 2) {
      if (isBeginnerProfile()) {
        content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 3 · Strategie</div><h3>Scegli due strumenti da provare</h3><p>Leggi le quattro schede e scegli esattamente due strategie. Nella prova le userai una alla volta. Tempo previsto: 8 minuti.</p></div><div class="study-choice-count" id="strategyCount">${state.chosen.length}/2 scelte</div></div><div class="strategy-library">${beginnerStrategies.map((strategy, index) => `<article class="strategy-guide"><div class="strategy-guide-top"><div><span class="strategy-index">${String(index + 1).padStart(2, '0')}</span><h4>${strategy.name}</h4><p>${strategy.summary}</p></div><label class="strategy-pick"><input type="checkbox" name="study-strategy" value="${index}" ${state.chosen.includes(index) ? 'checked' : ''}><span>Scegli questa</span></label></div><details><summary>Guarda i passaggi e un esempio</summary><div class="strategy-detail"><div class="strategy-when"><b>Quando è utile</b><span>${strategy.when}</span></div><div class="study-infographic" aria-label="Procedura in quattro passaggi per ${strategy.name}">${strategy.steps.map((step, stepIndex) => `<div><span>${stepIndex + 1}</span><b>${step}</b></div>`).join('')}</div><div class="strategy-examples"><div><b>Esempio sul testo</b><p>${strategy.example}</p></div><div><b>Attenzione</b><p>${strategy.avoid}</p></div></div><div class="strategy-try"><b>Nella prova</b>${strategy.practice}</div></div></details></article>`).join('')}</div><div class="study-actions">${button('Torna alla mappa', 'back', false, true)}${button('Prepara il testo sugli Egizi', 'exercise', state.chosen.length !== 2)}</div>`;
      } else {
        content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 3 · Capire prima di scegliere</div><h3>Come funzionano le strategie efficaci</h3><p>Apri le schede, osserva la procedura in quattro mosse e poi scegli esattamente due strategie da sperimentare. Tempo previsto: 15–20 minuti.</p></div><div class="study-choice-count" id="strategyCount">${state.chosen.length}/2 scelte</div></div><div class="strategy-library">${strategies.map((strategy, index) => `<article class="strategy-guide"><div class="strategy-guide-top"><div><span class="strategy-index">${String(index + 1).padStart(2, '0')}</span><h4>${strategy.name}</h4><p>${strategy.summary}</p></div><label class="strategy-pick"><input type="checkbox" name="study-strategy" value="${index}" ${state.chosen.includes(index) ? 'checked' : ''}><span>Scegli questa</span></label></div><details><summary>Scopri come funziona</summary><div class="strategy-detail"><div class="strategy-when"><b>Quando è utile</b><span>${strategy.when}</span></div><div class="study-infographic" aria-label="Procedura in quattro passaggi per ${strategy.name}">${strategy.steps.map((step, stepIndex) => `<div><span>${stepIndex + 1}</span><b>${step}</b></div>`).join('')}</div><div class="strategy-examples"><div><b>Esempio concreto</b><p>${strategy.example}</p></div><div><b>Errore da evitare</b><p>${strategy.avoid}</p></div></div><div class="strategy-try"><b>Prova lampo</b>${strategy.practice}</div></div></details></article>`).join('')}</div><div class="study-actions">${button('Torna alla mappa', 'back', false, true)}${button('Prepara la prova guidata', 'exercise', state.chosen.length !== 2)}</div>`;
      }
    } else if (state.step === 3) {
      const sample = samples[state.sample];
      if (isBeginnerProfile()) {
        const selectedStrategies = state.chosen.map(index => beginnerStrategies[index]);
        content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 4 · Laboratorio di storia</div><h3>Vivere lungo il Nilo · 25 minuti</h3><p>Segui i sette passaggi nell’ordine. Il testo è accessibile, ma le domande chiedono di capire informazioni, ordine e cause.</p></div><div class="study-choice-count">${state.exercise.filter(Boolean).length}/7 passaggi</div></div><div class="profile-activity"><b>Prova assegnata · ${sample.level}</b><span>${sample.title}. Lessico controllato, guida esplicita e domande di comprensione e ragionamento.</span></div><article class="practice-text"><div class="kicker">Testo di storia</div><h4>${sample.title}</h4>${sample.text.map(paragraph => `<p>${paragraph}</p>`).join('')}</article><div class="guided-practice">
          <section class="guided-step"><div class="guided-step-number">1<span>2 min</span></div><div><h4>Capisci l’obiettivo</h4><p>Leggi il titolo e la domanda-guida. Alla fine dovrai spiegare non solo che cosa dava il Nilo, ma anche che cosa facevano le persone.</p><div class="guided-prompt"><b>Domanda-guida</b>${sample.focus}</div>${exerciseCheck(0, 'Ho capito quale risposta devo costruire.')}</div></section>
          <section class="guided-step"><div class="guided-step-number">2<span>4 min</span></div><div><h4>Leggi e dai un titolo ai paragrafi</h4><p>Leggi una volta tutto il testo. Poi scrivi accanto a ogni paragrafo un titolo di massimo cinque parole.</p><div class="guided-hint"><b>Controllo</b>I quattro titoli devono essere diversi e mostrare come cambia l’argomento.</div>${exerciseCheck(1, 'Ho scritto un titolo breve per ogni paragrafo.')}</div></section>
          <section class="guided-step"><div class="guided-step-number">3<span>3 min</span></div><div><h4>Chiarisci le parole importanti</h4><p>Cerca nel testo le parole <strong>rive</strong>, <strong>fertile</strong>, <strong>argini</strong> e <strong>scribi</strong>. Prova prima a capirle dalla frase, poi controlla qui sotto.</p><div class="guided-hint"><b>Piccolo glossario</b>Rive: terre ai lati del fiume. Fertile: adatta a far crescere le piante. Argini: rialzi che contengono l’acqua. Scribi: persone che sapevano scrivere e registravano informazioni.</div>${exerciseCheck(2, 'Ho formulato un’ipotesi e controllato le quattro parole.')}</div></section>
          <section class="guided-step"><div class="guided-step-number">4<span>4 min</span></div><div><h4>Costruisci la catena</h4><p>Senza copiare frasi intere, scrivi cinque passaggi dal livello dell’acqua alla conservazione del raccolto. Collega i passaggi con parole come <em>lascia</em>, <em>permette</em>, <em>quindi</em>.</p>${exerciseCheck(3, 'Ho creato cinque passaggi e indicato almeno due relazioni.')}</div></section>
          <section class="guided-step"><div class="guided-step-number">5<span>4 min</span></div><div><h4>Applica: ${selectedStrategies[0].name}</h4><p>${selectedStrategies[0].practice}</p><div class="guided-hint"><b>Attenzione</b>${selectedStrategies[0].avoid}</div>${exerciseCheck(4, `Ho applicato ${selectedStrategies[0].name.toLowerCase()} e controllato il risultato.`)}</div></section>
          <section class="guided-step"><div class="guided-step-number">6<span>4 min</span></div><div><h4>Applica: ${selectedStrategies[1].name}</h4><p>${selectedStrategies[1].practice}</p><div class="guided-hint"><b>Attenzione</b>${selectedStrategies[1].avoid}</div>${exerciseCheck(5, `Ho applicato ${selectedStrategies[1].name.toLowerCase()} e controllato il risultato.`)}</div></section>
          <section class="guided-step"><div class="guided-step-number">7<span>8 min</span></div><div><h4>Rispondi senza copiare</h4><p>Copri il brano e rispondi alle cinque domande con frasi complete. Per l’ultima usa almeno due informazioni del testo. Poi riapri, controlla e correggi in un altro colore.</p><ol class="recall-prompts">${sample.prompts.map(prompt => `<li>${prompt}</li>`).join('')}</ol><label class="recall-field"><span>Le mie risposte</span><textarea id="studyRecall" rows="9">${state.recall}</textarea></label><button class="btn secondary" data-study-action="model" ${state.recall.trim().length < 80 ? 'disabled' : ''}>${state.reveal ? 'Nascondi la soluzione-modello' : 'Confronta con la soluzione-modello'}</button>${state.reveal ? `<div class="model-answer"><b>Soluzione-modello</b><p>${sample.model}</p><span>La tua risposta può usare parole diverse. Controlla soprattutto ordine, cause e informazioni essenziali.</span></div>` : ''}${exerciseCheck(6, 'Ho risposto senza copiare, confrontato e corretto ciò che mancava.')}</div></section>
        </div>${renderStudyMap(sample)}<div class="study-question reflection-block"><p>Quale passaggio ti è stato più utile?</p>${[['obiettivo', 'Capire prima che cosa dovevo trovare.'], ['catena', 'Mettere in ordine fatti, cause e conseguenze.'], ['controllo', 'Rispondere senza testo e poi correggere.']].map(([value, label]) => `<label class="study-option"><input type="radio" name="study-reflection" value="${value}" ${state.reflection === value ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div><div class="study-actions">${button('Torna alle strategie', 'back', false, true)}${button('Costruisci il mio piano', 'plan', state.exercise.length !== 7 || !state.exercise.every(Boolean) || !state.reflection)}</div>`;
      } else {
        const selectedStrategies = state.chosen.map(index => strategies[index]);
        content.innerHTML = `<div class="study-stage-head"><div><div class="kicker">Fase 4 · Laboratorio</div><h3>Prova guidata · 20 minuti</h3><p>Non devi cercare nulla: scegli uno dei tre testi e segui i passaggi nell’ordine. Spunta una fase soltanto quando l’hai conclusa.</p></div><div class="study-choice-count">${state.exercise.filter(Boolean).length}/5 fasi</div></div><div class="sample-picker" role="group" aria-label="Scegli il testo di prova">${samples.map((item, index) => `<button data-study-sample="${index}" class="sample-button ${state.sample === index ? 'active' : ''}" aria-pressed="${state.sample === index}"><b>${item.label}</b><span>${item.title.replace(`${item.label} · `, '')}</span></button>`).join('')}</div><article class="practice-text"><div class="kicker">Testo didattico originale StradiLab</div><h4>${sample.title}</h4>${sample.text.map(paragraph => `<p>${paragraph}</p>`).join('')}</article>${renderStudyMap(sample)}<aside class="pair-check"><div><div class="kicker">Facoltativo · controllo a coppie</div><h4>Confronta la tua mappa con un compagno</h4><p>Mostratevi solo i nodi e le frecce, senza correggervi a vicenda. Ognuno indica una relazione chiara e una da rendere più precisa.</p><ul><li>Quale nodo avete scelto entrambi?</li><li>Quale freccia spiega meglio il brano?</li><li>Che cosa cambiereste, e perché?</li></ul></div><label class="guided-check"><input type="checkbox" name="study-pair-check"><span>Abbiamo confrontato le mappe e motivato almeno una modifica.</span></label></aside><div class="guided-practice">
        <section class="guided-step"><div class="guided-step-number">1<span>2 min</span></div><div><h4>Orienta la lettura</h4><p>Leggi titolo e domanda-guida. Trasformala in un obiettivo: al termine dovrai rispondere senza guardare.</p><div class="guided-prompt"><b>Domanda-guida</b>${sample.focus}</div>${exerciseCheck(0, 'Ho capito quale risposta devo costruire.')}</div></section>
        <section class="guided-step"><div class="guided-step-number">2<span>3 min</span></div><div><h4>Prima lettura attiva</h4><p>Leggi il testo una volta. Dopo ogni paragrafo scrivi a margine una frase di massimo sette parole. Non evidenziare più di una frase per paragrafo.</p>${exerciseCheck(1, 'Ho individuato l’idea centrale dei tre paragrafi.')}</div></section>
        <section class="guided-step"><div class="guided-step-number">3<span>5 min</span></div><div><h4>Applica: ${selectedStrategies[0].name}</h4><p>${selectedStrategies[0].practice}</p><div class="guided-hint"><b>Non saltare il controllo.</b> ${selectedStrategies[0].avoid}</div>${exerciseCheck(2, `Ho applicato ${selectedStrategies[0].name.toLowerCase()} e controllato il risultato.`)}</div></section>
        <section class="guided-step"><div class="guided-step-number">4<span>5 min</span></div><div><h4>Applica: ${selectedStrategies[1].name}</h4><p>${selectedStrategies[1].practice}</p><div class="guided-hint"><b>Non saltare il controllo.</b> ${selectedStrategies[1].avoid}</div>${exerciseCheck(3, `Ho applicato ${selectedStrategies[1].name.toLowerCase()} e controllato il risultato.`)}</div></section>
        <section class="guided-step"><div class="guided-step-number">5<span>5 min</span></div><div><h4>Richiamo finale senza testo</h4><p>Copri il brano e rispondi alle tre domande. Non cercare frasi perfette: rendi visibili ciò che ricordi e i collegamenti.</p><ol class="recall-prompts">${sample.prompts.map(prompt => `<li>${prompt}</li>`).join('')}</ol><label class="recall-field"><span>Scrivi qui la tua ricostruzione</span><textarea id="studyRecall" rows="7">${state.recall}</textarea></label><button class="btn secondary" data-study-action="model" ${state.recall.trim().length < 30 ? 'disabled' : ''}>${state.reveal ? 'Nascondi la soluzione-modello' : 'Confronta con la soluzione-modello'}</button>${state.reveal ? `<div class="model-answer"><b>Soluzione-modello</b><p>${sample.model}</p><span>Non deve essere identica alla tua: controlla presenza delle relazioni essenziali e correggi in un altro colore.</span></div>` : ''}${exerciseCheck(4, 'Ho risposto senza testo, confrontato e corretto ciò che mancava.')}</div></section>
        </div><div class="study-question reflection-block"><p>Che cosa hai notato?</p>${[['utile', 'Le strategie mi hanno mostrato cosa sapevo davvero.'], ['difficile', 'È stato difficile, ma ora so quale passaggio allenare.'], ['riprovare', 'Riproverò con un testo più breve e lo stesso procedimento.']].map(([value, label]) => `<label class="study-option"><input type="radio" name="study-reflection" value="${value}" ${state.reflection === value ? 'checked' : ''}><span>${label}</span></label>`).join('')}</div><div class="study-actions">${button('Torna alle strategie', 'back', false, true)}${button('Costruisci il piano', 'plan', state.exercise.length !== 5 || !state.exercise.every(Boolean) || !state.reflection)}</div>`;
      }
    } else {
      if (isBeginnerProfile()) {
        const selectedNames = state.chosen.map(index => beginnerStrategies[index].name);
        const reflectionLabels = { obiettivo: 'capire prima che cosa dovevo trovare', catena: 'mettere in ordine fatti, cause e conseguenze', controllo: 'rispondere senza testo e poi correggere' };
        content.innerHTML = `<h3>5. Il mio piano per 7 giorni</h3><p>Quattro prove brevi da 15 minuti. Ogni volta usa un testo di una materia che stai studiando.</p><div class="study-card"><h4>Giorno 1 · Capire e dividere</h4><p>Leggo titolo e consegna, scrivo l’obiettivo e divido il lavoro in passaggi. Poi leggo il testo e do un titolo a ogni paragrafo.</p></div><div class="study-card"><h4>Giorno 2 · Ricordare</h4><p>Senza guardare, scrivo quattro idee del testo del giorno prima. Riapro e aggiungo in un altro colore ciò che manca.</p></div><div class="study-card"><h4>Giorno 4 · Collegare</h4><p>Creo una catena di cinque fatti. Uso frecce e parole come “perché”, “poi” e “quindi” per mostrare le relazioni.</p></div><div class="study-card"><h4>Giorno 7 · Verificare e correggere</h4><p>Preparo tre domande, rispondo senza aiuti e registro un errore: che cosa mancava, perché e come lo correggo.</p></div><section class="study-recap"><div class="kicker">Il tuo metodo</div><h4>Prima, durante, dopo</h4><p><strong>Prima:</strong> chiarisco l’obiettivo e preparo i passaggi.</p><p><strong>Durante:</strong> uso ${selectedNames.join(' e ')}.</p><p><strong>Dopo:</strong> controllo che cosa ricordo, correggo e decido quando riprovare.</p><p><strong>Passaggio risultato più utile:</strong> ${reflectionLabels[state.reflection]}.</p></section><div class="study-result show"><strong>Percorso completato · circa 50 minuti</strong><br>Hai osservato il tuo metodo, scelto due strategie, lavorato su un testo di storia e costruito un piano di sette giorni.<br><span class="welcome-line">La guida resta disponibile: con la pratica potrai usare gli stessi passaggi in modo sempre più autonomo.</span></div><div class="study-actions">${button('Rivedi la prova sugli Egizi', 'back', false, true)}${button('Ricomincia', 'restart', false, true)}${button('Salva come PDF', 'pdf')}</div>`;
      } else {
        content.innerHTML = `<h3>5. Il tuo piano per 7 giorni</h3><p>Trasforma l’esperimento in una routine breve e verificabile. Tempo previsto: 10 minuti.</p><div class="study-card"><h4>La mia routine</h4><p><strong>Prima:</strong> definisco un obiettivo concreto. <strong>Durante:</strong> uso ${state.chosen.map(index => strategies[index].name).join(' e ')}. <strong>Dopo:</strong> richiamo senza libro e registro un errore utile.</p></div><div class="study-card"><h4>Impegno concreto</h4><p>Per sette giorni farò quattro blocchi da 25 minuti, con telefono fuori portata. Riprenderò lo stesso contenuto in almeno tre giorni diversi e controllerò ciò che ricordo senza aiuti.</p></div><section class="study-recap"><div class="kicker">Il tuo riepilogo</div><h4>Che cosa hai scelto e sperimentato</h4><p><strong>Brano:</strong> ${samples[state.sample].title}</p><p><strong>Strategie:</strong> ${state.chosen.map(index => strategies[index].name).join(' · ')}</p><p><strong>La tua riflessione:</strong> ${state.reflection}</p><p><strong>Passo successivo:</strong> riprendi la mappa e il richiamo tra tre giorni, poi registra che cosa è migliorato.</p></section><div class="study-result show"><strong>Percorso completato · circa 65–70 minuti</strong><br>Hai osservato il tuo metodo, riconosciuto punti di forza e fragilità, compreso e provato due strategie e progettato un’applicazione settimanale.<br><span class="welcome-line">Continua così: ogni prova ti aiuta a conoscere meglio come impari.</span><br><strong>Benvenuto allo Stradivari!</strong></div><div class="study-actions">${button('Rivedi la prova', 'back', false, true)}${button('Ricomincia', 'restart', false, true)}${button('Salva come PDF', 'pdf')}</div>`;
      }
    }

    const profilePicker = content.querySelector('.sample-picker');
    if (profilePicker) {
      const sample = currentSample();
      profilePicker.insertAdjacentHTML('beforebegin', `<div class="profile-activity"><b>Prova assegnata · ${sample.level}</b><span>${sample.title}. Il testo e le domande sono adattati al profilo che hai scelto.</span></div>`);
      profilePicker.setAttribute('aria-label', 'Prova assegnata in base a classe e indirizzo');
      profilePicker.style.display = 'none';
      const stageDescription = content.querySelector('.study-stage-head p');
      if (stageDescription) stageDescription.textContent = 'Non devi cercare nulla: la prova è selezionata in base a classe e indirizzo. Segui i passaggi nell’ordine.';
    }
    if (isBeginnerProfile()) {
      const mapNote = content.querySelector('.map-note');
      if (mapNote) mapNote.innerHTML = '<strong>Controlla la tua catena.</strong> Confronta i cinque nodi con il tuo tentativo. Non devono essere identici: verifica che siano presenti ordine e relazioni tra acqua, lavoro e raccolto.';
    }
    content.querySelectorAll('[data-study-profile]').forEach(input => input.addEventListener('change', () => {
      state.year = '1';
      state.school = document.getElementById('studySchool').value;
      state.answers = [];
      state.chosen = [];
      state.exercise = [];
      state.reflection = '';
      state.recall = '';
      state.reveal = false;
      applyProfile();
      render();
    }));
    content.querySelectorAll('input[name="study-strategy"]').forEach(input => input.addEventListener('change', () => {
      const selected = [...content.querySelectorAll('input[name="study-strategy"]:checked')].map(item => Number(item.value));
      if (selected.length > 2) { input.checked = false; return; }
      state.chosen = selected;
      document.getElementById('strategyCount').textContent = `${selected.length}/2 scelte`;
      content.querySelector('[data-study-action="exercise"]').disabled = selected.length !== 2;
    }));
    content.querySelectorAll('input[name^="study-exercise"]').forEach((input, index) => input.addEventListener('change', () => { state.exercise[index] = input.checked; render(); }));
    content.querySelectorAll('input[name="study-reflection"]').forEach(input => input.addEventListener('change', () => { state.reflection = input.value; render(); }));
    const recall = document.getElementById('studyRecall');
    recall?.addEventListener('input', () => {
      state.recall = recall.value;
      const modelButton = content.querySelector('[data-study-action="model"]');
      if (modelButton) modelButton.disabled = state.recall.trim().length < (isBeginnerProfile() ? 80 : 30);
    });
  }

  document.addEventListener('click', event => {
    const sampleTrigger = event.target.closest('[data-study-sample]');
    if (sampleTrigger) {
      state.sample = Number(sampleTrigger.dataset.studySample);
      state.exercise = Array(5).fill(false);
      state.reflection = '';
      state.recall = '';
      state.reveal = false;
      render();
      return;
    }
    const trigger = event.target.closest('[data-study-action]');
    if (!trigger) return;
    const action = trigger.dataset.studyAction;
    if (action === 'diagnose') {
      state.answers = questions.map((_, index) => { const checked = document.querySelector(`input[name="study-q${index}"]:checked`); return checked ? Number(checked.value) : undefined; });
      if (state.answers.some(value => value === undefined)) { alert('Completa tutte le domande per ottenere la mappa.'); return; }
      state.step = 1;
    } else if (action === 'strategies') state.step = 2;
    else if (action === 'exercise') { state.exercise = Array(isBeginnerProfile() ? 7 : 5).fill(false); state.reflection = ''; state.recall = ''; state.reveal = false; state.step = 3; }
    else if (action === 'model') { state.reveal = !state.reveal; render(); return; }
    else if (action === 'plan') state.step = 4;
    else if (action === 'back') state.step = Math.max(0, state.step - 1);
    else if (action === 'restart') Object.assign(state, { step: 0, answers: [], chosen: [], exercise: [], reflection: '', sample: 0, recall: '', reveal: false });
    else if (action === 'pdf') {
      document.getElementById('downloadPdf')?.click();
      return;
    }
    render();
    content.scrollIntoView({ behavior: 'smooth', block: 'start' });
    document.dispatchEvent(new CustomEvent('stradivari-progress'));
  });

  window.StradivariStudy = { completed: () => state.step === 4 ? 5 : state.step, total: 5, getResults: () => ({ step: state.step, sample: samples[state.sample]?.title, strategies: state.chosen.map(index => currentStrategyLibrary()[index]?.name).filter(Boolean), reflection: state.reflection, completed: state.step === 4 }) };
  document.addEventListener('profilechange', updateSteps);
  render();
})();
